/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.markConsult.gui;

import br.com.markConsult.classesMetodos.ExamesTableModel;
import br.com.markConsult.classesMetodos.ExamesTableModel1;
import br.com.markConsult.classesMetodos.FixedLengthDocument;
import br.com.markConsult.classesMetodos.FuncaoTableModel;
import br.com.markConsult.classesMetodos.RiscosTableModel;
import br.com.markConsult.classesMetodos.RiscosTableModel1;
import br.com.markConsult.classesMetodos.SetorTableModel;
import br.com.markConsult.dao.CadEmpresaDAO;
import br.com.markConsult.dao.CadPCMSODAO;
import br.com.markConsult.dao.CadPeriodicidadeDAO;
import br.com.markConsult.entidades.Empresa;
import br.com.markConsult.entidades.Exame;
import br.com.markConsult.entidades.Funcao;
import br.com.markConsult.entidades.Periodicidade;
import br.com.markConsult.entidades.Risco;
import br.com.markConsult.entidades.Setor;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Jeferson
 */
public class CadPCMSO extends javax.swing.JInternalFrame {
private boolean okselecionado = false;
    List<Risco> espcialidades;
    private final SetorTableModel modelSetor;
    private final FuncaoTableModel modelFuncao;
    private final RiscosTableModel1 modelRisco;
    private final ExamesTableModel1 modelExame;
    /**
     * Creates new form CadPCMSO
     */
    public CadPCMSO() {
        initComponents();
        modelSetor = new SetorTableModel();
        jT_setor.setModel(modelSetor);
        
        modelFuncao = new FuncaoTableModel();
        jT_funcao.setModel(modelFuncao);
        
        modelRisco = new RiscosTableModel1();
        jT_risco.setModel(modelRisco);
        
        modelExame = new ExamesTableModel1();
        jT_exames.setModel(modelExame);
       

        
          tf_nomeEmpresa.setDocument(new FixedLengthDocument(70));
//        jTRiscos.getColumnModel().getColumn(0).setMinWidth(15);
//        jTRiscos.getColumnModel().getColumn(1).setPreferredWidth(200);
//        jTRiscos.getSelectionModel().setSelectionInterval(0, 0);
        
        
//        jTRiscos.setAutoCreateRowSorter(true);
//        
//        TableRowSorter<RiscoTableModel> sorter = new TableRowSorter<>((RiscoTableModel) jTRiscos.getModel());  
//            jTRiscos.setRowSorter(sorter);
//        
//        
//        JTableHeader header = jTRiscos.getTableHeader();  
//        header.addMouseListener(new MouseAdapter() {  
//  
//            @Override  
//            public void mouseClicked(MouseEvent e) {  
//                JTable table = ((JTableHeader) e.getSource()).getTable();  
//                TableColumnModel colModel = table.getColumnModel();  
//                int vColIndex = colModel.getColumnIndexAtX(e.getX());  
//                int mColIndex = table.convertColumnIndexToModel(vColIndex);  
//                if (vColIndex == -1) {  
//                    return;  
//                }  
//                int ordenacao = mColIndex; //criei esta váriavel ordenacao;  
//            }  
//        }); 
//        
//         tf_dado.requestFocus();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_setor = new javax.swing.JTable();
        bt_inseriSetor = new javax.swing.JButton();
        bt_rmSetor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_funcao = new javax.swing.JTable();
        bt_inseriFuncao = new javax.swing.JButton();
        bt_rmFuncao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jC_setores = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_risco = new javax.swing.JTable();
        bt_inseriRisco = new javax.swing.JButton();
        bt_rmRisco = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_exames = new javax.swing.JTable();
        bt_inseriExame = new javax.swing.JButton();
        bt_rmExame = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jC_funcoes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jC_setores2 = new javax.swing.JComboBox();
        jC_periodidade = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        tf_idEmpresa = new javax.swing.JTextField();
        tf_nomeEmpresa = new javax.swing.JTextField();
        tf_cnpj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de PCMSO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/help.png"))); // NOI18N

        jT_setor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jT_setor);

        bt_inseriSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/add-icon.png"))); // NOI18N
        bt_inseriSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inseriSetorActionPerformed(evt);
            }
        });

        bt_rmSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Action-remove-icon.png"))); // NOI18N
        bt_rmSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rmSetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_rmSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_inseriSetor)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_rmSetor)
                    .addComponent(bt_inseriSetor))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Setores", jPanel2);

        jT_funcao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jT_funcao);

        bt_inseriFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/add-icon.png"))); // NOI18N
        bt_inseriFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inseriFuncaoActionPerformed(evt);
            }
        });

        bt_rmFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Action-remove-icon.png"))); // NOI18N
        bt_rmFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rmFuncaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Setor:");

        jC_setores.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jC_setoresPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jC_setores, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 405, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_rmFuncao)
                .addGap(7, 7, 7)
                .addComponent(bt_inseriFuncao)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jC_setores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_rmFuncao)
                    .addComponent(bt_inseriFuncao))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Funções", jPanel1);

        jT_risco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jT_risco);

        bt_inseriRisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/add-icon.png"))); // NOI18N
        bt_inseriRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inseriRiscoActionPerformed(evt);
            }
        });

        bt_rmRisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Action-remove-icon.png"))); // NOI18N
        bt_rmRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rmRiscoActionPerformed(evt);
            }
        });

        jT_exames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jT_exames);

        bt_inseriExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/add-icon.png"))); // NOI18N
        bt_inseriExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inseriExameActionPerformed(evt);
            }
        });

        bt_rmExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Action-remove-icon.png"))); // NOI18N
        bt_rmExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rmExameActionPerformed(evt);
            }
        });

        jLabel4.setText("Função:");

        jC_funcoes.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jC_funcoesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RISCOS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("EXAMES");
        jLabel6.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel7.setText("Setor:");

        jC_setores2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jC_setores2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jC_periodidade.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jC_periodidadePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel8.setText("Periodicidade:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_periodidade, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_rmRisco)
                        .addGap(4, 4, 4)
                        .addComponent(bt_inseriRisco))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_rmExame)
                        .addGap(4, 4, 4)
                        .addComponent(bt_inseriExame))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jC_setores2, 0, 352, Short.MAX_VALUE)
                            .addComponent(jC_funcoes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jC_setores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jC_funcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_rmRisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_inseriRisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_rmExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_inseriExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jC_periodidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Riscos/Exames", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empresa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel3.setText("Empresa:");

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tf_idEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_idEmpresaFocusLost(evt);
            }
        });
        tf_idEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_idEmpresaKeyPressed(evt);
            }
        });

        tf_nomeEmpresa.setEditable(false);

        tf_cnpj.setEditable(false);

        jLabel1.setText("CNPJ:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cnpj)
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5)
                    .addComponent(tf_idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_inseriSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inseriSetorActionPerformed
        if (!tf_idEmpresa.getText().equals("")) {
            CadPCMSODAO dao = new CadPCMSODAO();
            BuscaSetor buscaSetor = new  BuscaSetor(null, true);
            buscaSetor.setVisible(true);

            if (buscaSetor.okselecionado()) {
                int id_empresa = Integer.parseInt(tf_idEmpresa.getText());
                dao.inseriEmpresaSetor(id_empresa, buscaSetor.retornEspSele().getId());
                Empresa emp = new Empresa();
                emp.setId(id_empresa);
                mostraSetoresFuncoes(emp);

            }
            buscaSetor.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma Empresa!");
        }

    }//GEN-LAST:event_bt_inseriSetorActionPerformed

    private void bt_rmSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rmSetorActionPerformed
        int setorSele = jT_setor.getSelectedRow();

        if (setorSele >= 0 && !tf_idEmpresa.getText().equals("")) {
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Excluir setor Selecionado?", "Exclusão ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                Setor set = modelSetor.getItem(setorSele);
                CadPCMSODAO dao = new CadPCMSODAO();
                Empresa emp = new Empresa();
                emp.setId(Integer.parseInt(tf_idEmpresa.getText()));
                dao.rmSetorPorEmpresa(emp, set);
                mostraSetoresFuncoes(emp);

            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Setor!");
        }
    }//GEN-LAST:event_bt_rmSetorActionPerformed

    private void bt_inseriFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inseriFuncaoActionPerformed
        if (jC_setores.getSelectedIndex()>0) {

            CadPCMSODAO dao = new CadPCMSODAO();
            BuscaFuncao buscaFuncao = new  BuscaFuncao(null, true);
            buscaFuncao.setVisible(true);

            if (buscaFuncao.okselecionado()) {
                int id_empresa = Integer.parseInt(tf_idEmpresa.getText());
                Setor setor = null;

                if (jC_setores.getSelectedIndex() != 0) {
                    setor = (Setor) jC_setores.getSelectedItem();
                }
                dao.inseriEmpresaSetorFuncao(id_empresa, setor.getId() ,buscaFuncao.retornEspSele().getId());
                Empresa emp = new Empresa();
                emp.setId(id_empresa);
                buscaFuncoesPorSetor(emp, setor);

            }
            buscaFuncao.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Setor!");
        }
    }//GEN-LAST:event_bt_inseriFuncaoActionPerformed

    private void bt_rmFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rmFuncaoActionPerformed
        int funcaoSele = jT_funcao.getSelectedRow();

        if (funcaoSele >= 0 && !tf_idEmpresa.getText().equals("")) {
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Excluir Função Selecionada?", "Exclusão ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                CadPCMSODAO dao = new CadPCMSODAO();
                Empresa emp = new Empresa();
                emp.setId(Integer.parseInt(tf_idEmpresa.getText()));

                Setor set = (Setor) jC_setores.getSelectedItem();
                Funcao fun = modelFuncao.getItem(funcaoSele);
                dao.rmFuncaoPorEmpresa(emp, set, fun);
                buscaFuncoesPorSetor(emp,set);
                

            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Setor!");
        }
    }//GEN-LAST:event_bt_rmFuncaoActionPerformed

    private void jC_setoresPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jC_setoresPopupMenuWillBecomeInvisible
        if (!"".equals(tf_idEmpresa.getText()) && jC_setores.getSelectedIndex() > 0) {
            Empresa emp = new Empresa();
            emp.setId(Integer.parseInt(tf_idEmpresa.getText())) ;
            buscaFuncoesPorSetor(emp, (Setor) jC_setores.getSelectedItem());
        }else{
            modelFuncao.limpaLista();
            
        }

    }//GEN-LAST:event_jC_setoresPopupMenuWillBecomeInvisible

    private void bt_inseriRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inseriRiscoActionPerformed
        if (jC_funcoes.getSelectedIndex()>0) {

            CadPCMSODAO dao = new CadPCMSODAO();
            BuscaRisco buscaRisco = new  BuscaRisco(null, true);
            buscaRisco.setVisible(true);

            if (buscaRisco.okselecionado()) {
                int id_empresa = Integer.parseInt(tf_idEmpresa.getText());
                Funcao funcao = null;

                if (jC_funcoes.getSelectedIndex() != 0) {
                    funcao = (Funcao) jC_funcoes.getSelectedItem();
                }
                dao.inseriEmpresaFuncaoRisco(id_empresa, funcao.getId() ,buscaRisco.retornEspSele().getId());
                Empresa emp = new Empresa();
                emp.setId(id_empresa);
                buscaRiscos(emp, funcao);

            }
            buscaRisco.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma Função!");
        }
    }//GEN-LAST:event_bt_inseriRiscoActionPerformed

    private void bt_rmRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rmRiscoActionPerformed
        int riscoSele = jT_risco.getSelectedRow();

        if (riscoSele >= 0 && !tf_idEmpresa.getText().equals("")) {
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Excluir Risco Selecionado?", "Exclusão ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                CadPCMSODAO dao = new CadPCMSODAO();
                Empresa emp = new Empresa();
                emp.setId(Integer.parseInt(tf_idEmpresa.getText()));

                Funcao func = (Funcao) jC_funcoes.getSelectedItem();
                Risco risco = modelRisco.getItem(riscoSele);
                dao.rmRiscoPorEmpFuncao(risco);
                buscaRiscos(emp,func);

            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Risco!");
        }
    }//GEN-LAST:event_bt_rmRiscoActionPerformed

    private void bt_inseriExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inseriExameActionPerformed
        if (jC_setores2.getSelectedIndex()>0) {

             }else{
            JOptionPane.showMessageDialog(null, "Selecione um Setor!");
            return;
        }
        
        if (jC_funcoes.getSelectedIndex()>0) {

             }else{
            JOptionPane.showMessageDialog(null, "Selecione uma Função!");
            return;
        }
        if (jC_periodidade.getSelectedIndex() > 0) {
   

            CadPCMSODAO dao = new CadPCMSODAO();
            BuscaExames buscaExames = new  BuscaExames(null, true);
            buscaExames.setVisible(true);

            if (buscaExames.okselecionado()) {
                int id_empresa = Integer.parseInt(tf_idEmpresa.getText());
                
                
                 Funcao funcao = null;
                if (jC_funcoes.getSelectedIndex() != 0) {
                     funcao  = (Funcao) jC_funcoes.getSelectedItem();
                    
                }
             Periodicidade  periodicidade = null;
                if (jC_periodidade.getSelectedIndex() != 0) {
                    periodicidade = (Periodicidade) jC_periodidade.getSelectedItem();
                
                }
                
                Empresa empresa = new Empresa();
                empresa.setId(id_empresa);
                dao.inseriEmpresaFuncaoExame(empresa, funcao ,buscaExames.retornEspSele(), periodicidade);
                buscaExames(empresa, funcao, periodicidade);

            }
            buscaExames.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma periodicidade!");
        }
    }//GEN-LAST:event_bt_inseriExameActionPerformed

    private void bt_rmExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rmExameActionPerformed
        int exameSele = jT_exames.getSelectedRow();

        if (exameSele >= 0 && !tf_idEmpresa.getText().equals("")) {
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Excluir Exame Selecionado?", "Exclusão ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                CadPCMSODAO dao = new CadPCMSODAO();
                Empresa emp = new Empresa();
                emp.setId(Integer.parseInt(tf_idEmpresa.getText()));

                Funcao func = (Funcao) jC_funcoes.getSelectedItem();
                Periodicidade periodicidade = (Periodicidade) jC_periodidade.getSelectedItem();
                Exame exa = modelExame.getItem(exameSele);
                dao.rmExamePorEmpFuncao(exa);
                buscaExames(emp,func,periodicidade);

            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Exame!");
        }
    }//GEN-LAST:event_bt_rmExameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        telBuscEmp();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tf_idEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_idEmpresaFocusLost

        String id = tf_idEmpresa.getText();
        if (id.equals("")) {
            limpaTudo();
        } else {
            buscaPorId(id);
            
        }

    }//GEN-LAST:event_tf_idEmpresaFocusLost

    private void tf_idEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idEmpresaKeyPressed
        if (tf_idEmpresa.isEditable()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                telBuscEmp();

            }
        }
    }//GEN-LAST:event_tf_idEmpresaKeyPressed

    private void jC_setores2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jC_setores2PopupMenuWillBecomeInvisible
         if (!"".equals(tf_idEmpresa.getText()) && jC_setores2.getSelectedIndex() > 0) {
            Empresa emp = new Empresa();
            emp.setId(Integer.parseInt(tf_idEmpresa.getText())) ;
            Setor set = (Setor) jC_setores2.getSelectedItem();
            atualizaJCFuncoes(emp,set);
            limpaTableRiscosExames();
        }else{
             jC_funcoes.removeAllItems();
             jC_periodidade.removeAllItems();
             limpaTableRiscosExames();
             
         }
        
        
    }//GEN-LAST:event_jC_setores2PopupMenuWillBecomeInvisible

    private void jC_periodidadePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jC_periodidadePopupMenuWillBecomeInvisible
       if (!"".equals(tf_idEmpresa.getText()) && jC_funcoes.getSelectedIndex() > 0 && jC_periodidade.getSelectedIndex() > 0) {
            Empresa emp = new Empresa();
            emp.setId(Integer.parseInt(tf_idEmpresa.getText())) ;
            Funcao fun = (Funcao) jC_funcoes.getSelectedItem();
            Periodicidade periodicidade = (Periodicidade) jC_periodidade.getSelectedItem();
            buscaExames(emp, fun, periodicidade);
        }else{
            limpaTableRiscosExames();
        }
    }//GEN-LAST:event_jC_periodidadePopupMenuWillBecomeInvisible

    private void jC_funcoesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jC_funcoesPopupMenuWillBecomeInvisible
       if (!"".equals(tf_idEmpresa.getText()) && jC_funcoes.getSelectedIndex() > 0) {
            atualizaJCPeriodicidade();
            Empresa emp = new Empresa();
            emp.setId(Integer.parseInt(tf_idEmpresa.getText())) ;
            Funcao fun = (Funcao) jC_funcoes.getSelectedItem();
            limpaTableRiscosExames();
            buscaRiscos(emp,fun );
        }else{
             jC_periodidade.removeAllItems();
             limpaTableRiscosExames();
             
         }
    }//GEN-LAST:event_jC_funcoesPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_inseriExame;
    private javax.swing.JButton bt_inseriFuncao;
    private javax.swing.JButton bt_inseriRisco;
    private javax.swing.JButton bt_inseriSetor;
    private javax.swing.JButton bt_rmExame;
    private javax.swing.JButton bt_rmFuncao;
    private javax.swing.JButton bt_rmRisco;
    private javax.swing.JButton bt_rmSetor;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jC_funcoes;
    private javax.swing.JComboBox jC_periodidade;
    private javax.swing.JComboBox jC_setores;
    private javax.swing.JComboBox jC_setores2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jT_exames;
    private javax.swing.JTable jT_funcao;
    private javax.swing.JTable jT_risco;
    private javax.swing.JTable jT_setor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tf_cnpj;
    private javax.swing.JTextField tf_idEmpresa;
    private javax.swing.JTextField tf_nomeEmpresa;
    // End of variables declaration//GEN-END:variables
private void telBuscEmp() {
        BuscaEmpresas pcp = new BuscaEmpresas(null, true);
        pcp.getRootPane().setWindowDecorationStyle(JRootPane.COLOR_CHOOSER_DIALOG);
        pcp.setVisible(true);

        if (pcp.okselecionado()) {

            Empresa emp = pcp.retornCliSele();
            mostraEempresa(emp);
            mostraSetoresFuncoes(emp);
            
        }
    }

    private void mostraEempresa(Empresa emp) {
       
        if (emp != null) {
          tf_idEmpresa.setText(emp.getId().toString());
          tf_nomeEmpresa.setText(emp.getFantasia());  
          tf_cnpj.setText(emp.getCnpj());
        }
    }
    
    private void buscaPorId(String id) {
        CadEmpresaDAO dao = new CadEmpresaDAO();
        Empresa empresa = dao.buscEmpPid(Integer.parseInt(id));
        if (empresa == null) {
            JOptionPane.showMessageDialog(null, "Empresa não cadastrada!");
            tf_idEmpresa.requestFocus();
            limpaTudo();
        } else {
            mostraEempresa(empresa);
            mostraSetoresFuncoes(empresa);
            estadoInicial();
        }

    }

    private void mostraSetoresFuncoes(Empresa emp){
        if (emp != null) {
            CadPCMSODAO dao = new CadPCMSODAO();
            List<Setor> s = dao.buscSetorPorEmpresa(emp);
            modelSetor.listar(s);
             jC_setores.removeAllItems();
             jC_setores2.removeAllItems();
             jC_setores.addItem("Selecione");
             jC_setores2.addItem("Selecione");
             for (Setor setor : s) {
             jC_setores.addItem(setor);  
             jC_setores2.addItem(setor);  
        }
           
        }
    
}
    
    private void atualizaJCFuncoes(Empresa emp, Setor set){
    CadPCMSODAO dao = new CadPCMSODAO();
    List<Funcao> f = dao.buscFuncaoPorSetorEmpresa(emp, set);
        jC_funcoes.removeAllItems();
        jC_funcoes.addItem("Selecione");
        for (Funcao func : f) {
          jC_funcoes.addItem(func);  
        }
    
}
    private void atualizaJCPeriodicidade(){
    CadPeriodicidadeDAO dao = new CadPeriodicidadeDAO();
    List<Periodicidade> p = dao.buscaPeriodicidadees("", 'e');
        jC_periodidade.removeAllItems();
        jC_periodidade.addItem("Selecione");
        for (Periodicidade peri : p) {
          jC_periodidade.addItem(peri);  
        }
    
}
    
    private void buscaFuncoesPorSetor(Empresa emp, Setor set){
         CadPCMSODAO dao = new CadPCMSODAO();
        List<Funcao> funcoes = dao.buscFuncaoPorSetorEmpresa(emp, set);
        modelFuncao.listar(funcoes);
        
        
    }
    
    private void buscaRiscos(Empresa emp, Funcao func){
         CadPCMSODAO dao = new CadPCMSODAO();
      
       modelRisco.listar(dao.buscRiscoPorFuncaoEmpresa(emp, func));
        
    }
    
    private void buscaExames(Empresa emp, Funcao func, Periodicidade p){
         CadPCMSODAO dao = new CadPCMSODAO();
         modelExame.listar(dao.buscExamePorFuncaoPeriod(emp, func,p));
        
    }
    
    
    private void limpaTudo(){
       
       tf_nomeEmpresa.setText("");
       tf_cnpj.setText("");
       jC_setores.removeAllItems();
       jC_funcoes.removeAllItems();
        
       modelSetor.limpaLista();
       modelFuncao.limpaLista();
       modelRisco.limpaLista();
       modelExame.limpaLista();
    }
    
    
     private void estadoInicial(){
       jC_setores.setSelectedIndex(0);
       modelFuncao.limpaLista();
       modelRisco.limpaLista();
       modelExame.limpaLista();
    }
     
     
    private void limpaTableRiscosExames(){
        
        modelRisco.limpaLista();
        modelExame.limpaLista();
    }
}
