/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.markConsult.gui;

import br.com.markConsult.classesMetodos.FixedLengthDocument;
import br.com.markConsult.classesMetodos.IntegerDocument;
import br.com.markConsult.dao.CadEmpresaDAO;
import br.com.markConsult.dao.CadPacienteDAO;
import br.com.markConsult.dao.CadConvenioDAO;
import br.com.markConsult.dao.CadFuncaoDAO;
import br.com.markConsult.dao.ICadPacienteDAO;
import br.com.markConsult.entidades.Cep;
import br.com.markConsult.entidades.Convenio;
import br.com.markConsult.entidades.Empresa;
import br.com.markConsult.entidades.Funcao;
import br.com.markConsult.entidades.Paciente;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.InputMismatchException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author jeferson
 */
public class CadPaciente extends javax.swing.JInternalFrame {

    String data = (new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date(System.currentTimeMillis())));
    int inserir_alterar = 0;

    /**
     * Creates new form CadPaciente
     */
    public CadPaciente() {
        initComponents();
        estadoBotoes("inicial");

        tf_codigo.setDocument(new IntegerDocument(10));
        tf_codigoEmpresa.setDocument(new IntegerDocument(10));
        tf_nuConvenio.setDocument(new FixedLengthDocument(20));
        tf_idConvenio.setDocument(new IntegerDocument(10));
        tf_nome.setDocument(new FixedLengthDocument(120));
        tf_nomeMae.setDocument(new FixedLengthDocument(120));
        tf_NomePai.setDocument(new FixedLengthDocument(120));
        tf_municipio.setDocument(new FixedLengthDocument(80));
        tf_uf.setDocument(new FixedLengthDocument(2));
        tf_logradouro.setDocument(new FixedLengthDocument(120));
        tf_numero.setDocument(new FixedLengthDocument(10));
        tf_bairro.setDocument(new FixedLengthDocument(65));
        tf_complemento.setDocument(new FixedLengthDocument(65));
        jf_foneFixo.setDocument(new FixedLengthDocument(25));
        tf_celular1.setDocument(new FixedLengthDocument(25));
        tf_celular2.setDocument(new FixedLengthDocument(25));
        tf_celular3.setDocument(new FixedLengthDocument(25));
        tf_obser.setDocument(new FixedLengthDocument(150));
        tf_cpf.setDocument(new FixedLengthDocument(14));
        tf_rg.setDocument(new FixedLengthDocument(15));

        atualizaTela();

        bt_buscar.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_sair = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_novo = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        bt_ultimo = new javax.swing.JButton();
        bt_avançar = new javax.swing.JButton();
        bt_primeiro = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        bt_marcar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        tf_celular2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_dataNasc = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            tf_dataNasc = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel3 = new javax.swing.JLabel();
        tf_celular3 = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_rg = new javax.swing.JTextField();
        jC_tipoSag = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_idConvenio = new javax.swing.JTextField();
        tf_nomeConv = new javax.swing.JTextField();
        tf_celular1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_nuConvenio = new javax.swing.JTextField();
        cbxDesabilitado = new java.awt.Checkbox();
        jLabel22 = new javax.swing.JLabel();
        bt_buscConv = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tf_cpf = new javax.swing.JFormattedTextField();
        jf_foneFixo = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nomeMae = new javax.swing.JTextField();
        tf_NomePai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_codigoEmpresa = new javax.swing.JTextField();
        bt_buscaEmpresa = new javax.swing.JButton();
        tf_nomeEmpresa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jL_Funcao = new javax.swing.JLabel();
        bt_funcao = new javax.swing.JButton();
        tf_idFuncao = new javax.swing.JTextField();
        tf_nomeFuncao = new javax.swing.JTextField();
        tf_idadePaciente = new javax.swing.JTextField();
        tf_obser = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_codigo_cep = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("#####-###");
            tf_codigo_cep = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        tf_municipio = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_logradouro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_bairro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_complemento = new javax.swing.JTextField();
        tf_numero = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_uf = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Pacientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/help.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setToolTipText("");

        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Log-Out-icon.png"))); // NOI18N
        bt_sair.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sair", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Action-edit-icon.png"))); // NOI18N
        bt_editar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/App-floppy-icon.png"))); // NOI18N
        bt_salvar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salvar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_salvar.setIconTextGap(2);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/new-file-icon.png"))); // NOI18N
        bt_novo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/trash-icon.png"))); // NOI18N
        bt_excluir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_excluir.setIconTextGap(2);
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_cancelar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Extras-Close-icon.png"))); // NOI18N
        bt_cancelar.setAutoscrolls(true);
        bt_cancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancelar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_cancelar.setIconTextGap(2);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Search-icon.png"))); // NOI18N
        bt_buscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });
        bt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_buscarKeyPressed(evt);
            }
        });

        bt_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/hide-right-icon.png"))); // NOI18N
        bt_ultimo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ultimo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ultimoActionPerformed(evt);
            }
        });

        bt_avançar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/navigate-right-icon.png"))); // NOI18N
        bt_avançar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avançar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_avançar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_avançarActionPerformed(evt);
            }
        });

        bt_primeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/hide-left-icon.png"))); // NOI18N
        bt_primeiro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primeiro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_primeiroActionPerformed(evt);
            }
        });

        bt_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/navigate-left-icon.png"))); // NOI18N
        bt_voltar.setToolTipText("");
        bt_voltar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Voltar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });

        bt_marcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/consultas.png"))); // NOI18N
        bt_marcar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 11))); // NOI18N
        bt_marcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_marcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(bt_marcar)
                .addGap(0, 0, 0)
                .addComponent(bt_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_avançar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_avançar, bt_buscar, bt_cancelar, bt_editar, bt_excluir, bt_marcar, bt_novo, bt_primeiro, bt_sair, bt_salvar, bt_ultimo, bt_voltar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_ultimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_avançar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_primeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_marcar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel29.setText("Celular:");

        jLabel12.setText("Fone Fixo:");

        jLabel13.setText("Celular:");

        jLabel4.setText("Data Nasc.:");

        tf_dataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_dataNascFocusLost(evt);
            }
        });

        jLabel3.setText("Celular:");

        tf_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_nomeFocusLost(evt);
            }
        });
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo Sanguineo:");

        tf_rg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_rgFocusLost(evt);
            }
        });

        jC_tipoSag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ignorado", "O+", " A+", "B+", "AB+", "O-", "A-", "B-", "AB-" }));

        jLabel18.setText("Código:");

        jLabel2.setText("Convênio:");

        tf_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codigoFocusLost(evt);
            }
        });
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });
        tf_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codigoKeyPressed(evt);
            }
        });

        tf_idConvenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_idConvenioFocusLost(evt);
            }
        });
        tf_idConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idConvenioActionPerformed(evt);
            }
        });
        tf_idConvenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_idConvenioKeyPressed(evt);
            }
        });

        jLabel1.setText("Nº Convênio:");

        jLabel23.setText("RG:");

        tf_nuConvenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_nuConvenioFocusLost(evt);
            }
        });
        tf_nuConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nuConvenioActionPerformed(evt);
            }
        });

        cbxDesabilitado.setLabel("Desabilitado");

        jLabel22.setText("CPF:");

        bt_buscConv.setText("...");
        bt_buscConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscConvActionPerformed(evt);
            }
        });

        jLabel24.setText("Nome:");

        tf_cpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_cpfFocusLost(evt);
            }
        });
        tf_cpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cpfMouseClicked(evt);
            }
        });

        jLabel7.setText("Idade:");

        jLabel8.setText("Nome mãe:");

        jLabel9.setText("Nome pai:");

        jLabel10.setText("Empresa:");

        tf_codigoEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codigoEmpresaFocusLost(evt);
            }
        });
        tf_codigoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoEmpresaActionPerformed(evt);
            }
        });
        tf_codigoEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codigoEmpresaKeyPressed(evt);
            }
        });

        bt_buscaEmpresa.setText("...");
        bt_buscaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscaEmpresaActionPerformed(evt);
            }
        });

        jLabel11.setText("Função:");

        jL_Funcao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Funcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Funcao.setText("*");

        bt_funcao.setText("...");
        bt_funcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_funcaoActionPerformed(evt);
            }
        });

        tf_idFuncao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_idFuncaoFocusLost(evt);
            }
        });
        tf_idFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idFuncaoActionPerformed(evt);
            }
        });
        tf_idFuncao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_idFuncaoKeyPressed(evt);
            }
        });

        tf_nomeFuncao.setEditable(false);

        tf_idadePaciente.setEditable(false);

        jLabel14.setText("Observação");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jL_Funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jf_foneFixo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(tf_rg))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(6, 6, 6)
                                .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(tf_celular1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(tf_celular2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_celular3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tf_dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_idadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jC_tipoSag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tf_nomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_NomePai))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_idFuncao)
                            .addComponent(tf_codigoEmpresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(tf_idConvenio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_codigo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nuConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDesabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bt_funcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_buscConv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_buscaEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nomeEmpresa)
                                    .addComponent(tf_nomeConv)
                                    .addComponent(tf_nomeFuncao)))))
                    .addComponent(tf_obser))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDesabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_nuConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_buscConv)
                    .addComponent(tf_idConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomeConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_codigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscaEmpresa)
                    .addComponent(tf_nomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_funcao)
                    .addComponent(jLabel11)
                    .addComponent(jL_Funcao)
                    .addComponent(tf_idFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomeFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_NomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tf_idadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jC_tipoSag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel22)
                        .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(tf_dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(tf_celular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jf_foneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_celular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_celular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_obser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados", jPanel4);

        jLabel5.setText("Cep:");

        jLabel26.setText("Município:");

        jLabel17.setText("Logradouro:");

        jLabel20.setText("Bairro:");

        jLabel21.setText("Complemento:");

        jLabel19.setText("Número:");

        jLabel27.setText("UF:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tf_logradouro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tf_codigo_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_municipio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_numero)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_complemento)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_codigo_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(tf_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(tf_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188))
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        tf_nuConvenio.requestFocus();
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void tf_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codigoFocusLost

        if (tf_codigo.isEditable()) {
            String id = tf_codigo.getText();
            if (id.equals("")) {
                atualizaTela();
            } else {
                buscaPorId(id);
            }
        }
    }//GEN-LAST:event_tf_codigoFocusLost

    private void tf_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codigoKeyPressed
        if (tf_codigo.isEditable()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                telBuscaPaciente();

            }
        }

    }//GEN-LAST:event_tf_codigoKeyPressed

    private void tf_idConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idConvenioActionPerformed

        tf_codigoEmpresa.requestFocus();
    }//GEN-LAST:event_tf_idConvenioActionPerformed

    private void tf_idConvenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_idConvenioFocusLost
        if (tf_idConvenio.isEditable()) {
            if (!tf_idConvenio.getText().equals("")) {
                buscaConvenio();
            } else {
                tf_nomeConv.setText("");
            }
        }
    }//GEN-LAST:event_tf_idConvenioFocusLost

    private void tf_idConvenioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idConvenioKeyPressed
        if (tf_idConvenio.isEditable()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                telBuscaConvenio();

            }
        }
    }//GEN-LAST:event_tf_idConvenioKeyPressed

    private void tf_nuConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nuConvenioActionPerformed
       tf_nome.requestFocus();
    }//GEN-LAST:event_tf_nuConvenioActionPerformed

    private void bt_buscConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscConvActionPerformed
        telBuscaConvenio();
    }//GEN-LAST:event_bt_buscConvActionPerformed

    private void tf_cpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cpfMouseClicked
        String remove = removerMascara(tf_cpf.getText());
        tf_cpf.setText(remove);
    }//GEN-LAST:event_tf_cpfMouseClicked

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed

        inserir_alterar = 1;
        estadoBotoes("novo");
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        if (verificaCampos() == false) {
            if (temConvenio()) {
                String numConvenio = tf_nuConvenio.getText();
                String idConvenio = tf_idConvenio.getText();
                Integer idConven = null;
                if (!idConvenio.equals("")) {
                    idConven = Integer.parseInt(idConvenio);
                }
                String nome = tf_nome.getText();
                String nuCep = tf_codigo_cep.getText();
                String municipio = tf_municipio.getText();
                String uf = tf_uf.getText();
                String logradouro = tf_logradouro.getText();
                String numero = tf_numero.getText();
                String bairro = tf_bairro.getText();
                String complemento = tf_complemento.getText();
                String cpf = tf_cpf.getText();
                String rg = tf_rg.getText();
                Date dataNasc = null;
                Date dataCadastro = null;
                try {
                    dataNasc = converte(tf_dataNasc.getText());
                    //dataCadastro = converte(data);
                } catch (ParseException ex) {
                    //Logger.getLogger(CadPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    dataCadastro = converte(data);
                } catch (ParseException ex) {
                    //Logger.getLogger(CadPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
                String tipSang = jC_tipoSag.getSelectedItem().toString();
                String fonefixo = jf_foneFixo.getText();
                String celular1 = tf_celular1.getText();
                String celular2 = tf_celular2.getText();
                String celular3 = tf_celular3.getText();
                String obs = tf_obser.getText();
                String nomeMae = tf_nomeMae.getText();
                String nomePai = tf_NomePai.getText();
                boolean desabilitado = cbxDesabilitado.getState();

                Empresa empresa = new Empresa();
                String codigoEmpresa = tf_codigoEmpresa.getText();
                Integer codigoEmp;
                if (!codigoEmpresa.equals("")) {
                    codigoEmp = Integer.parseInt(codigoEmpresa);
                    empresa.setId(codigoEmp);
                }
                Convenio Idconvenio = new Convenio(idConven, null);
                Cep cep = new Cep(null, nuCep, logradouro, bairro, municipio, uf);
                String idFuncao = tf_idFuncao.getText();
                Funcao funcao = new Funcao();
                
                if (!idFuncao.equals("")) {
                    funcao.setId(Integer.parseInt(idFuncao));
                }
                if (inserir_alterar == 0) {

                    ICadPacienteDAO dao = new CadPacienteDAO();
                    Paciente paciente = new Paciente(null, numConvenio, Idconvenio, nome, "", numero,
                            complemento, cpf, rg, dataNasc, tipSang, fonefixo, celular1, celular2, celular3,
                            obs, cep, desabilitado, dataCadastro, nomeMae, nomePai, empresa, funcao);
                    try {
                        int id = dao.insePaciente(paciente);
                        paciente.setId(id);
                        tf_codigo.setText("" + id);
                    } catch (SQLException ex) {

                    }

                }

                if (inserir_alterar == 1) {
                    int codigo = Integer.parseInt(tf_codigo.getText());
                    ICadPacienteDAO dao = new CadPacienteDAO();
                    Paciente paciente = new Paciente(codigo, numConvenio, Idconvenio, nome, "", numero,
                            complemento, cpf, rg, dataNasc, tipSang, fonefixo, celular1, celular2, celular3,
                            obs, cep, desabilitado, nomeMae, nomePai, empresa, funcao);
                    dao.altPaciente(paciente);
                }
                inserir_alterar = 0;

                estadoBotoes("salvar");

            } else {
                JOptionPane.showMessageDialog(null, "Favor informe o convênio");
            }
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed

        limpaCampos();
        estadoBotoes("novo");
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Excluir " + tf_nome.getText() + "?", "Exclusão ", JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tf_codigo.getText());
            ICadPacienteDAO dao = new CadPacienteDAO();
            boolean excludo = dao.rmPaciente(id);
            if (excludo) {
                atualizaTela();
                estadoBotoes("inicial");
            } else {
                JOptionPane.showMessageDialog(null, "Paciente não pode ser excluído porque está sendo referênciado em outro cadastro!");
            }

        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        String nome = "Deseja realmente cancelar?";
        int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome, "Cancelar ", JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION) {
            inserir_alterar = 0;
            estadoBotoes("cancelar");

        }
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        telBuscaPaciente();
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_buscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            telBuscaPaciente();
        }
    }//GEN-LAST:event_bt_buscarKeyPressed

    private void bt_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ultimoActionPerformed
        atualizaTela();
    }//GEN-LAST:event_bt_ultimoActionPerformed

    private void bt_avançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_avançarActionPerformed

        ICadPacienteDAO dao = new CadPacienteDAO();
        Paciente c = dao.mostrarProximo(Integer.parseInt(tf_codigo.getText()));
        mostrar_dados(c);
    }//GEN-LAST:event_bt_avançarActionPerformed

    private void bt_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_primeiroActionPerformed
        ICadPacienteDAO dao = new CadPacienteDAO();
        Paciente c = dao.mostrarPrimeiro();
        mostrar_dados(c);
    }//GEN-LAST:event_bt_primeiroActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed

        ICadPacienteDAO dao = new CadPacienteDAO();
        Paciente c = dao.mostrarAnterior(Integer.parseInt(tf_codigo.getText()));
        mostrar_dados(c);

    }//GEN-LAST:event_bt_voltarActionPerformed

    private void tf_dataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_dataNascFocusLost
        getIdade();
    }//GEN-LAST:event_tf_dataNascFocusLost

    private void tf_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nomeFocusLost
        if (tf_nome.isEditable()) {
            String nome = tf_nome.getText();
            if (!nome.equals("")) {
                buscaPacientePorNome(nome);
            }
        }
    }//GEN-LAST:event_tf_nomeFocusLost

    private void tf_rgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_rgFocusLost
        if (tf_rg.isEditable()) {
            String rg = tf_rg.getText();
            if (!rg.equals("")) {
                buscaPacientePorRG(rg);
            }
        }
    }//GEN-LAST:event_tf_rgFocusLost

    private void bt_marcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_marcarActionPerformed

        try {
            CadConsultaModal telCadCons = new CadConsultaModal(null, true);
            telCadCons.estadoBotoes("novo");
            telCadCons.novoCad(converte(data));
            Paciente c = new Paciente();
            c.setId(Integer.parseInt(tf_codigo.getText()));
            telCadCons.setPaciente(c);
            telCadCons.buscaPaciente();
            telCadCons.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(CadPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bt_marcarActionPerformed

    private void tf_codigoEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codigoEmpresaFocusLost
        if (tf_codigoEmpresa.isEditable()) {
            if (!tf_codigoEmpresa.getText().equals("")) {
                buscaEmpresa();
            } else {
                tf_nomeEmpresa.setText("");
            }
        }
    }//GEN-LAST:event_tf_codigoEmpresaFocusLost

    private void tf_codigoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoEmpresaActionPerformed
        tf_idFuncao.requestFocus();
    }//GEN-LAST:event_tf_codigoEmpresaActionPerformed

    private void bt_buscaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscaEmpresaActionPerformed
        telBuscaEmpresa();
    }//GEN-LAST:event_bt_buscaEmpresaActionPerformed

    private void tf_codigoEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codigoEmpresaKeyPressed
        if (tf_codigoEmpresa.isEditable()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                telBuscaEmpresa();

            }
        }
    }//GEN-LAST:event_tf_codigoEmpresaKeyPressed

    private void tf_idFuncaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_idFuncaoFocusLost
        if (tf_idFuncao.isEditable()) {
            if (!tf_idFuncao.getText().equals("")) {
                buscaFuncao();
            } else {
                tf_nomeFuncao.setText("");
            }
        }
    }//GEN-LAST:event_tf_idFuncaoFocusLost

    private void tf_idFuncaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idFuncaoKeyPressed
        if (tf_idFuncao.isEditable()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                telBuscaFuncao();

            }
        }
    }//GEN-LAST:event_tf_idFuncaoKeyPressed

    private void tf_idFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idFuncaoActionPerformed
        tf_nomeMae.requestFocus();
    }//GEN-LAST:event_tf_idFuncaoActionPerformed

    private void bt_funcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_funcaoActionPerformed
        telBuscaFuncao();
    }//GEN-LAST:event_bt_funcaoActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        tf_idConvenio.requestFocus();
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void tf_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cpfFocusLost
        String cpf1 = removerMascara(tf_cpf.getText());
        if (!cpf1.equals("")) {

            boolean resultado = isCPF(cpf1);
            if (resultado == false) {
                JOptionPane.showMessageDialog(null, "CPF" + cpf1 + " não é válido");
                tf_cpf.requestFocus();
            } else {
                tf_cpf.setText(imprimeCPF(cpf1));
                ICadPacienteDAO dao = new CadPacienteDAO();
                String cp = tf_cpf.getText();
                List<Paciente> c = dao.buscaPaciente(cp, 't');
                if (!c.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "CPF já cadastrado!");
                    tf_cpf.requestFocus();
                }
            }

        }
    }//GEN-LAST:event_tf_cpfFocusLost

    private void tf_nuConvenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nuConvenioFocusLost
          if(!tf_nuConvenio.getText().equals("")){
            buscaPorNumCon(tf_nuConvenio.getText());
            }
    }//GEN-LAST:event_tf_nuConvenioFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_avançar;
    private javax.swing.JButton bt_buscConv;
    private javax.swing.JButton bt_buscaEmpresa;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_funcao;
    private javax.swing.JButton bt_marcar;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_primeiro;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_ultimo;
    private javax.swing.JButton bt_voltar;
    private java.awt.Checkbox cbxDesabilitado;
    private javax.swing.JComboBox jC_tipoSag;
    private javax.swing.JLabel jL_Funcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField jf_foneFixo;
    private javax.swing.JTextField tf_NomePai;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JFormattedTextField tf_celular1;
    private javax.swing.JTextField tf_celular2;
    private javax.swing.JTextField tf_celular3;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_codigoEmpresa;
    private javax.swing.JTextField tf_codigo_cep;
    private javax.swing.JTextField tf_complemento;
    private javax.swing.JFormattedTextField tf_cpf;
    private javax.swing.JFormattedTextField tf_dataNasc;
    private javax.swing.JTextField tf_idConvenio;
    private javax.swing.JTextField tf_idFuncao;
    private javax.swing.JTextField tf_idadePaciente;
    private javax.swing.JTextField tf_logradouro;
    private javax.swing.JTextField tf_municipio;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nomeConv;
    private javax.swing.JTextField tf_nomeEmpresa;
    private javax.swing.JTextField tf_nomeFuncao;
    private javax.swing.JTextField tf_nomeMae;
    private javax.swing.JTextField tf_nuConvenio;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_obser;
    private javax.swing.JTextField tf_rg;
    private javax.swing.JTextField tf_uf;
    // End of variables declaration//GEN-END:variables
 public static String formatarString(String texto, String mascara) throws ParseException {
        MaskFormatter mf = new MaskFormatter(mascara);
        mf.setValueContainsLiteralCharacters(false);
        return mf.valueToString(texto);

    }

    public static boolean isCPF(String CPF) {
// considera-se erro CPF's formados por uma sequencia de numeros iguais
        if (CPF.equals("00000000000") || CPF.equals("11111111111")
                || CPF.equals("22222222222") || CPF.equals("33333333333")
                || CPF.equals("44444444444") || CPF.equals("55555555555")
                || CPF.equals("66666666666") || CPF.equals("77777777777")
                || CPF.equals("88888888888") || CPF.equals("99999999999")
                || (CPF.length() != 11)) {
            return (false);
        }

        char dig10, dig11;
        int sm, i, r, num, peso;

// "try" - protege o codigo para eventuais erros de conversao de tipo (int)
        try {
// Calculo do 1o. Digito Verificador
            sm = 0;
            peso = 10;
            for (i = 0; i < 9; i++) {
// converte o i-esimo caractere do CPF em um numero:
// por exemplo, transforma o caractere '0' no inteiro 0        
// (48 eh a posicao de '0' na tabela ASCII)        
                num = (int) (CPF.charAt(i) - 48);
                sm = sm + (num * peso);
                peso = peso - 1;
            }

            r = 11 - (sm % 11);
            if ((r == 10) || (r == 11)) {
                dig10 = '0';
            } else {
                dig10 = (char) (r + 48); // converte no respectivo caractere numerico
            }
// Calculo do 2o. Digito Verificador
            sm = 0;
            peso = 11;
            for (i = 0; i < 10; i++) {
                num = (int) (CPF.charAt(i) - 48);
                sm = sm + (num * peso);
                peso = peso - 1;
            }

            r = 11 - (sm % 11);
            if ((r == 10) || (r == 11)) {
                dig11 = '0';
            } else {
                dig11 = (char) (r + 48);
            }

// Verifica se os digitos calculados conferem com os digitos informados.
            if ((dig10 == CPF.charAt(9)) && (dig11 == CPF.charAt(10))) {
                return (true);
            } else {
                return (false);
            }
        } catch (InputMismatchException erro) {
            return (false);
        }
    }

    public static String imprimeCPF(String CPF) {
        return (CPF.substring(0, 3) + "." + CPF.substring(3, 6) + "."
                + CPF.substring(6, 9) + "-" + CPF.substring(9, 11));
    }

    public String removerMascara(String str) {
        return str.replaceAll("\\D", "");

    }

    private void estadoBotoes(String botao) {
        if ("inicial".equals(botao)) {
            bt_novo.setEnabled(true);
            bt_cancelar.setEnabled(false);
            bt_editar.setEnabled(true);
            bt_buscar.setEnabled(true);
            bt_salvar.setEnabled(false);
            bt_excluir.setEnabled(true);
            bt_primeiro.setEnabled(true);
            bt_voltar.setEnabled(true);
            bt_avançar.setEnabled(true);
            bt_ultimo.setEnabled(true);
            bt_buscConv.setEnabled(false);
            bt_buscaEmpresa.setEnabled(false);
            bt_marcar.setEnabled(true);
            bt_funcao.setEnabled(false);

            tf_codigo.setEditable(true);
            tf_codigoEmpresa.setEditable(false);
            tf_nomeEmpresa.setEditable(false);
            tf_nome.setEditable(false);
            tf_nuConvenio.setEditable(false);
            tf_codigo_cep.setEditable(false);
            tf_municipio.setEditable(false);
            tf_uf.setEditable(false);
            tf_logradouro.setEditable(false);
            tf_numero.setEditable(false);
            tf_bairro.setEditable(false);
            tf_complemento.setEditable(false);
            tf_cpf.setEditable(false);
            tf_rg.setEditable(false);
            tf_dataNasc.setEditable(false);
            jC_tipoSag.setEditable(false);
            jC_tipoSag.setEnabled(false);
            jf_foneFixo.setEditable(false);
            tf_celular1.setEditable(false);
            tf_celular2.setEditable(false);
            tf_celular3.setEditable(false);
            tf_idConvenio.setEditable(false);
            tf_nomeConv.setEditable(false);
            tf_obser.setEditable(false);
            cbxDesabilitado.setEnabled(false);
            tf_nomeMae.setEditable(false);
            tf_NomePai.setEditable(false);
            tf_idFuncao.setEditable(false);

        }

        if ("novo".equals(botao)) {
            bt_novo.setEnabled(false);
            bt_cancelar.setEnabled(true);
            bt_editar.setEnabled(true);
            bt_buscar.setEnabled(false);
            bt_excluir.setEnabled(false);
            bt_editar.setEnabled(false);
            bt_salvar.setEnabled(true);
            bt_primeiro.setEnabled(false);
            bt_voltar.setEnabled(false);
            bt_avançar.setEnabled(false);
            bt_ultimo.setEnabled(false);
            bt_buscConv.setEnabled(true);
            bt_marcar.setEnabled(false);
            bt_buscaEmpresa.setEnabled(true);
            bt_funcao.setEnabled(true);

            tf_codigo.setEditable(false);
            tf_codigoEmpresa.setEditable(true);
            tf_nome.setEditable(true);
            tf_nuConvenio.setEditable(true);
            tf_codigo_cep.setEditable(true);
            tf_municipio.setEditable(true);
            tf_uf.setEditable(true);
            tf_logradouro.setEditable(true);
            tf_numero.setEditable(true);
            tf_bairro.setEditable(true);
            tf_complemento.setEditable(true);
            tf_cpf.setEditable(true);
            tf_rg.setEditable(true);
            tf_dataNasc.setEditable(true);
            jC_tipoSag.setEnabled(true);
            jf_foneFixo.setEditable(true);
            tf_celular1.setEditable(true);
            tf_celular2.setEditable(true);
            tf_celular3.setEditable(true);
            tf_idConvenio.setEditable(true);
            tf_obser.setEditable(true);
            cbxDesabilitado.setEnabled(true);
            tf_nomeMae.setEditable(true);
            tf_NomePai.setEditable(true);
            tf_idFuncao.setEditable(true);
        }

        if ("cancelar".equals(botao)) {
            atualizaTela();
            estadoBotoes("inicial");
        }
        if ("salvar".equals(botao)) {
            estadoBotoes("inicial");

        }

        if ("buscar".equals(botao)) {
            estadoBotoes("inicial");

        }

    }

    public Date converte(String dataNasc) throws ParseException {
        DateFormat forma = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date dat = new java.sql.Date(forma.parse(dataNasc).getTime());

        return dat;
    }

    private void atualizaTela() {
        ICadPacienteDAO dao = new CadPacienteDAO();
        Paciente c = dao.mostrarUltimo();
        mostrar_dados(c);
        jL_Funcao.setForeground(Color.black);
    }

    public void mostrar_dados(Paciente paciente) {
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        if (paciente != null) {
            tf_codigo.setText("" + paciente.getId());
            tf_nuConvenio.setText(paciente.getNumConvenio());
            tf_nome.setText(paciente.getNome());
            tf_nomeMae.setText(paciente.getNomeMae());
            tf_NomePai.setText(paciente.getNomePai());
            
            if (paciente.getConvenio().getId() > 0) {
                tf_idConvenio.setText(paciente.getConvenio().getId().toString());
                tf_nomeConv.setText(paciente.getConvenio().getDsConvenio());
            } else {
                tf_idConvenio.setText("");
                tf_nomeConv.setText("");
            }
            if (paciente.getEmpresa().getId() > 0) {
                tf_codigoEmpresa.setText("" + paciente.getEmpresa().getId());
                tf_nomeEmpresa.setText(paciente.getEmpresa().getFantasia());
            } else {
                tf_codigoEmpresa.setText("");
                tf_nomeEmpresa.setText("");
            }
            if (!paciente.getCep().getCodCep().equals("     -   ")) {
                tf_codigo_cep.setText(paciente.getCep().getCodCep());
            } else {
                tf_codigo_cep.setText("");
            }

            tf_municipio.setText(paciente.getCep().getCidade());
            tf_uf.setText(paciente.getCep().getUf());
            tf_logradouro.setText(paciente.getCep().getLogradouro());
            tf_numero.setText(paciente.getNumero());
            tf_bairro.setText(paciente.getCep().getBairro());
            tf_complemento.setText(paciente.getComplemento());
            tf_cpf.setText(paciente.getCpf());
            tf_rg.setText(paciente.getRg());

            if (paciente.getDataNasc() != null) {
                tf_dataNasc.setText(f.format(paciente.getDataNasc()));
                getIdade();

            } else {
                tf_dataNasc.setText("");
                getIdade();
            }

            jf_foneFixo.setText(paciente.getFoneFixo());
            tf_celular1.setText(paciente.getCelular1());
            tf_celular2.setText(paciente.getCelular2());
            tf_celular3.setText(paciente.getCelular3());
            tf_obser.setText(paciente.getObs());
            jC_tipoSag.setSelectedItem(paciente.getTipoSangue());
            cbxDesabilitado.setState(paciente.isDesabilitado());

            if (paciente.getFuncao().getId() > 0) {
                tf_idFuncao.setText(paciente.getFuncao().getId().toString());
                tf_nomeFuncao.setText(paciente.getFuncao().getNome());
            } else {
                tf_idFuncao.setText("");
                tf_nomeFuncao.setText("");
            }

        }
    }

    public void buscaPorId(String id) {
        ICadPacienteDAO dao = new CadPacienteDAO();
        Paciente paciente = dao.buscaPacientePorId(Integer.parseInt(id));
        if (paciente == null) {
            JOptionPane.showMessageDialog(null, "Paciente não cadastrado!");
            tf_codigo.requestFocus();
        }
        mostrar_dados(paciente);
    }

    public void buscaPacientePorNome(String nome) {
        CadPacienteDAO dao = new CadPacienteDAO();
        Paciente paciente = dao.buscPacientePrecadastro(nome, 'e');
        if (paciente != null) {
            String frase = "Já existe um Paciente com esse nome, deseja continuar?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, frase, "Cancelar ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                tf_idFuncao.requestFocus();
            } else {
                tf_nome.requestFocus();
            }
        }
    }

    public void buscaPacientePorRG(String rg) {
        CadPacienteDAO dao = new CadPacienteDAO();
        Paciente paciente = dao.buscPacientePrecadastro(rg, 'i');
        if (paciente != null) {
            String frase = "Já existe um Paciente com esse RG, deseja continuar?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, frase, "Cancelar ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                tf_cpf.requestFocus();
            } else {
                tf_rg.requestFocus();
            }
        }
    }

    public void buscaPorNumCon(String id) {
        ICadPacienteDAO dao = new CadPacienteDAO();
        Paciente paciente = dao.buscaPacientePorConsulta(id);
        if (paciente != null) {
            JOptionPane.showMessageDialog(null, "Paciente já cadastrado com esse número de convênio");
        }
        mostrar_dados(paciente);
    }

    public void buscaConvenio() {
        CadConvenioDAO dao = new CadConvenioDAO();
        Convenio convenio = dao.procuraPorID(Integer.parseInt(tf_idConvenio.getText()));
        if (convenio != null) {
            mostraConvenio(convenio);
        } else {
            JOptionPane.showMessageDialog(null, "Convênio  não cadastrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tf_idConvenio.requestFocus();
        }

    }

    public void telBuscaConvenio() {
        BuscaConvenios tc = new BuscaConvenios(null, true);
        tc.setVisible(true);
        if (tc.okselecionado()) {
            Convenio c = tc.retornEspSele();
            mostraConvenio(c);
        }
        tc.dispose();
    }

    private void mostraConvenio(Convenio convenio) {
        tf_idConvenio.setText(convenio.getId().toString());
        tf_nomeConv.setText(convenio.getDsConvenio());
    }

    public void buscaEmpresa() {
        CadEmpresaDAO dao = new CadEmpresaDAO();
        Empresa empresa = dao.buscaEmpresaPorId(Integer.parseInt(tf_codigoEmpresa.getText()));
        if (empresa != null) {
            mostraEmpresa(empresa);
        } else {
            JOptionPane.showMessageDialog(null, "Empresa  não cadastrada!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tf_codigoEmpresa.requestFocus();
        }

    }

    public void telBuscaEmpresa() {
        BuscaEmpresas tc = new BuscaEmpresas(null, true);
        tc.setVisible(true);

        if (tc.okselecionado()) {
            Empresa c = tc.retornCliSele();
            mostraEmpresa(c);
        }
        tc.dispose();
    }

    private void mostraEmpresa(Empresa empresa) {
        tf_codigoEmpresa.setText(empresa.getId().toString());
        tf_nomeEmpresa.setText(empresa.getFantasia());
    }

    public void buscaFuncao() {
        CadFuncaoDAO dao = new CadFuncaoDAO();
        Funcao f = dao.procuraPorID(Integer.parseInt(tf_idFuncao.getText()));
        if (f != null) {
            mostraFuncao(f);

        } else {
            JOptionPane.showMessageDialog(null, "Função  não cadastrada!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tf_idFuncao.requestFocus();
        }

    }

    public void telBuscaFuncao() {
        BuscaFuncao tc = new BuscaFuncao(null, true);
        tc.setVisible(true);
        if (tc.okselecionado()) {
            Funcao c = tc.retornEspSele();
            mostraFuncao(c);
        }
        tc.dispose();
    }

    private void mostraFuncao(Funcao funcao) {
        tf_idFuncao.setText(funcao.getId().toString());
        tf_nomeFuncao.setText(funcao.getNome());
    }

    public void telBuscaPaciente() {
        BuscaPacientesModal pcp = new BuscaPacientesModal(null, true);
        pcp.getRootPane().setWindowDecorationStyle(JRootPane.COLOR_CHOOSER_DIALOG);
        pcp.setVisible(true);

        if (pcp.okselecionado()) {
            Paciente c = pcp.retornCliSele();
            mostrar_dados(c);
        }

    }

    /**
     * Calcula a idade de acordo com a data passada.
     *
     * @author Isaias Pfaffenseller
     */
    public void getIdade() {
        Date dataNasc = null;
        try {
            dataNasc = converte(tf_dataNasc.getText());
        } catch (ParseException ex) {
            //Logger.getLogger(CadPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        Calendar dataNascimento = Calendar.getInstance();
        if (dataNasc != null) {
            dataNascimento.setTime(dataNasc);
            Calendar dataAtual = Calendar.getInstance();

            Integer diferencaMes = dataAtual.get(Calendar.MONTH) - dataNascimento.get(Calendar.MONTH);
            Integer diferencaDia = dataAtual.get(Calendar.DAY_OF_MONTH) - dataNascimento.get(Calendar.DAY_OF_MONTH);
            Integer idade = (dataAtual.get(Calendar.YEAR) - dataNascimento.get(Calendar.YEAR));

            if (diferencaMes < 0 || (diferencaMes == 0 && diferencaDia < 0)) {
                idade--;
            }
            tf_idadePaciente.setText(idade.toString());
        } else {
            tf_idadePaciente.setText("");
        }

    }

    private boolean temConvenio() {
        String idConvenio = tf_idConvenio.getText();
        return !"".equals(idConvenio);
    }

    public boolean verificaCampos() {
        boolean ok = false;
        if (tf_nomeFuncao.getText() == null) {
            jL_Funcao.setForeground(Color.red);
            ok = true;
        } else {
            jL_Funcao.setForeground(Color.black);
        }

        return ok;
    }

    private void limpaCampos() {
        tf_codigo.setText("");
        tf_nuConvenio.setText("");
        tf_idConvenio.setText("");
        tf_nomeConv.setText("");
        tf_codigoEmpresa.setText("");
        tf_nomeEmpresa.setText("");
        tf_nome.setText("");
        tf_codigo_cep.setText("");
        tf_municipio.setText("");
        tf_uf.setText("");
        tf_logradouro.setText("");
        tf_numero.setText("");
        tf_bairro.setText("");
        tf_complemento.setText("");
        tf_cpf.setText(null);
        tf_rg.setText("");
        tf_dataNasc.setText("");
        jf_foneFixo.setText("");
        tf_celular1.setText("");
        tf_celular2.setText("");
        tf_celular3.setText("");
        tf_obser.setText("");
        tf_idadePaciente.setText("");
        tf_nomeMae.setText("");
        tf_NomePai.setText("");
        tf_nuConvenio.requestFocus();
        tf_idFuncao.setText("");
        tf_nomeFuncao.setText("");
    }

}
