/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.markConsult.gui;

import br.com.markConsult.classesMetodos.IntegerDocument;
import br.com.markConsult.classesMetodos.Mascaras;
import br.com.markConsult.dao.CadProcedimentoDAO;
import br.com.markConsult.entidades.Procedimento;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Jeferson
 */
public class CadProcedimentoEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form CadProcedimentoEmpresa
     * @param parent
     * @param modal
     */
    public CadProcedimentoEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        URL url = this.getClass().getResource("/br/com/markConsult/imagens/help.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        
        tf_codigoProcedimento.setDocument(new IntegerDocument(10));
        tf_valor.setDocument(new Mascaras(10));
        
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);

        Action escapeAction = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_codigoProcedimento = new javax.swing.JTextField();
        bt_buscaProcedimento = new javax.swing.JButton();
        tf_nomeProcedimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir procedimento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Procedimento Empresa"));

        jLabel10.setText("Procedimento:");

        tf_codigoProcedimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codigoProcedimentoFocusLost(evt);
            }
        });
        tf_codigoProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoProcedimentoActionPerformed(evt);
            }
        });
        tf_codigoProcedimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codigoProcedimentoKeyPressed(evt);
            }
        });

        bt_buscaProcedimento.setText("...");
        bt_buscaProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscaProcedimentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_codigoProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_buscaProcedimento))
                    .addComponent(tf_valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nomeProcedimento, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_codigoProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscaProcedimento)
                    .addComponent(tf_nomeProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Inserir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscaProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscaProcedimentoActionPerformed
        telBuscaEmpresa();
    }//GEN-LAST:event_bt_buscaProcedimentoActionPerformed

    private void tf_codigoProcedimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codigoProcedimentoKeyPressed
        if (tf_codigoProcedimento.isEditable()) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                telBuscaEmpresa();

            }
        }
    }//GEN-LAST:event_tf_codigoProcedimentoKeyPressed

    private void tf_codigoProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoProcedimentoActionPerformed
        tf_valor.requestFocus();
    }//GEN-LAST:event_tf_codigoProcedimentoActionPerformed

    private void tf_codigoProcedimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codigoProcedimentoFocusLost
        if (tf_codigoProcedimento.isEditable()) {
            if (!tf_codigoProcedimento.getText().equals("")) {
                buscaProcedimento();
            } else {
                tf_nomeProcedimento.setText("");
            }
        }
    }//GEN-LAST:event_tf_codigoProcedimentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProcedimentoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CadProcedimentoEmpresa dialog = new CadProcedimentoEmpresa(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscaProcedimento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_codigoProcedimento;
    private javax.swing.JTextField tf_nomeProcedimento;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
        public void buscaProcedimento() {
            CadProcedimentoDAO dao = new CadProcedimentoDAO();
        Procedimento p = dao.procuraPorID(Integer.parseInt(tf_codigoProcedimento.getText()));
        if (p != null) {
            tf_codigoProcedimento.setText(p.getId().toString());
            tf_nomeProcedimento.setText(p.getDsProcedimento());

        } else {
            JOptionPane.showMessageDialog(null, "Procedimento  não cadastrada!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tf_codigoProcedimento.requestFocus();
        }

    }
    public void telBuscaEmpresa() {
        BuscaProcedimentos tc = new BuscaProcedimentos(null, true);
        tc.setVisible(true);

        if (tc.okselecionado()) {
            Procedimento p = tc.retornEspSele();
            tf_codigoProcedimento.setText(p.getId().toString());
            tf_nomeProcedimento.setText(p.getDsProcedimento());
        }
        tc.dispose();
    }

}
