/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.markConsult.gui;

import br.com.markConsult.dao.CadConsultasDAO;
import br.com.markConsult.entidades.Sessao;
import br.com.markConsult.entidades.Clinica;
import br.com.markConsult.entidades.CondPagto;
import br.com.markConsult.entidades.Convenio;
import br.com.markConsult.entidades.Empresa;
import br.com.markConsult.entidades.Paciente;
import br.com.markConsult.entidades.Usuario;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SwingWorker;

/**
 *
 * @author jeferson
 */
public class RelaConsultas extends javax.swing.JInternalFrame {
private String empresa;
private String paciente;
private String usuario;
private String conve;
private String status;
private String condPag;
private String ordem;
private String data = (new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date(System.currentTimeMillis())));

    /**
     * Creates new form RelaConsultas
     */
    public RelaConsultas() {
        initComponents();
        Calendar data1 = new GregorianCalendar();
        int priDiaMes = data1.getActualMinimum(Calendar.DAY_OF_MONTH);  
        data1.set(Calendar.DAY_OF_MONTH, priDiaMes);
        
     Date d = null;
    try {
         d = converte(new SimpleDateFormat("dd/MM/yyyy").format(data1.getTime()));
    } catch (ParseException ex) {
        Logger.getLogger(RelaConsultas.class.getName()).log(Level.SEVERE, null, ex);
    }
        Date dt = null;
    try {
        dt = converte(data);
    } catch (ParseException ex) {
        Logger.getLogger(RelaConsultas.class.getName()).log(Level.SEVERE, null, ex);
    }
        tf_dataIni.setDate(d);
        tf_dataFin.setDate(dt);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_dataFin = new com.toedter.calendar.JDateChooser("dd/MM/yyyy" , "##/##/####" , ' ');
        cb_stat = new javax.swing.JComboBox();
        cb_paciente = new javax.swing.JComboBox();
        tf_dataIni = new com.toedter.calendar.JDateChooser("dd/MM/yyyy" , "##/##/####" , ' ');
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb_conv = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_medico = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cb_emprea = new javax.swing.JComboBox();
        cb_ordem = new javax.swing.JComboBox();
        cb_condPagt = new javax.swing.JComboBox();
        tf_medico = new javax.swing.JTextField();
        tf_empresa = new javax.swing.JTextField();
        tf_paciente = new javax.swing.JTextField();
        tf_convenio = new javax.swing.JTextField();
        tf_condpgto = new javax.swing.JTextField();
        bt_cancelar = new javax.swing.JButton();
        bt_gerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Relatório de Consultas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/help.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório de Consultas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel6.setText("Convênio:");

        cb_stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Aberta", "Encerrado", "Cancelado", "Faltou", "Aguardando", "Em consulta" }));

        cb_paciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Selecionar" }));
        cb_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pacienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Status:");

        jLabel4.setText("Paciente:");

        jLabel3.setText("Período final:");

        jLabel1.setText("Período inicial:");

        cb_conv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Selecionar" }));
        cb_conv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_convActionPerformed(evt);
            }
        });

        jLabel2.setText("Cond. Pagto:");

        jLabel7.setText("Ordenação:");

        jLabel8.setText("Médico:");

        cb_medico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Selecionar" }));
        cb_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_medicoActionPerformed(evt);
            }
        });

        jLabel9.setText("Empresa:");

        cb_emprea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Selecionar" }));
        cb_emprea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_empreaActionPerformed(evt);
            }
        });

        cb_ordem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Data Consulta", "Paciente", "Convênio", "Cond. Pagto.", "Status" }));

        cb_condPagt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Selecionar" }));
        cb_condPagt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_condPagtActionPerformed(evt);
            }
        });

        tf_medico.setEditable(false);

        tf_empresa.setEditable(false);

        tf_paciente.setEditable(false);

        tf_convenio.setEditable(false);

        tf_condpgto.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_condPagt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_conv, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_paciente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_medico, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_emprea, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_dataIni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_dataFin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 249, Short.MAX_VALUE))
                            .addComponent(tf_medico)
                            .addComponent(tf_empresa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_paciente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_convenio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_condpgto)))
                    .addComponent(cb_stat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_ordem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_dataIni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_dataFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_emprea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_conv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_convenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_condPagt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_condpgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ordem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_gerar.setText("Gerar");
        bt_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancelar)
                    .addComponent(bt_gerar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pacienteActionPerformed
        int sele = cb_paciente.getSelectedIndex();
        if (sele == 1) {
            cb_paciente.setPopupVisible(false);
            telaBuscaClient();
        }else{
            tf_paciente.setText("");
        }

    }//GEN-LAST:event_cb_pacienteActionPerformed

    private void cb_convActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_convActionPerformed
        int sele = cb_conv.getSelectedIndex();
        if (sele == 1) {
            cb_conv.setPopupVisible(false);
            telBuscaConvenio();
        }else{
            tf_convenio.setText("");
        }
    }//GEN-LAST:event_cb_convActionPerformed

    private void cb_condPagtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_condPagtActionPerformed
        int sele = cb_condPagt.getSelectedIndex();
        if (sele == 1) {
            cb_condPagt.setPopupVisible(false);
            telBuscaConpagt();
        }else{
            tf_condpgto.setText("");
        }
    }//GEN-LAST:event_cb_condPagtActionPerformed

    private void cb_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_medicoActionPerformed
        int sele = cb_medico.getSelectedIndex();
        if (sele == 1) {
            cb_medico.setPopupVisible(false);
            telabuscMedicos();
        }else{
            tf_medico.setText("");
        }
    }//GEN-LAST:event_cb_medicoActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerarActionPerformed
        final Progress p = new Progress();
        p.setVisible(true);
        SwingWorker worker = new SwingWorker(){
            @Override
            protected Object doInBackground() throws Exception {
                gerarRel(); // meu processo demorado
                return null;
            }
            @Override
            protected void done() {
                p.setVisible(false);
            }
        };
        worker.execute();

    }//GEN-LAST:event_bt_gerarActionPerformed

    private void cb_empreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_empreaActionPerformed
        int sele = cb_emprea.getSelectedIndex();
        if (sele == 1) {
            cb_emprea.setPopupVisible(false);
            telBuscaEmpresa();
        }else{
            tf_empresa.setText("");
        }
    }//GEN-LAST:event_cb_empreaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_gerar;
    private javax.swing.JComboBox cb_condPagt;
    private javax.swing.JComboBox cb_conv;
    private javax.swing.JComboBox cb_emprea;
    private javax.swing.JComboBox cb_medico;
    private javax.swing.JComboBox cb_ordem;
    private javax.swing.JComboBox cb_paciente;
    private javax.swing.JComboBox cb_stat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_condpgto;
    private javax.swing.JTextField tf_convenio;
    private com.toedter.calendar.JDateChooser tf_dataFin;
    private com.toedter.calendar.JDateChooser tf_dataIni;
    private javax.swing.JTextField tf_empresa;
    private javax.swing.JTextField tf_medico;
    private javax.swing.JTextField tf_paciente;
    // End of variables declaration//GEN-END:variables
public void telaBuscaClient(){
        BuscaPacientesModal telBuscClie = new BuscaPacientesModal(null, true);
        telBuscClie.setVisible(true);
        Paciente c;
        if (telBuscClie.okselecionado()) {
             c = telBuscClie.retornCliSele();
            if (c != null) {
                paciente = c.getId().toString();
                tf_paciente.setText(c.getNome());
                }
            }else  {
                cb_paciente.setSelectedIndex(0);   
            }
        }

public void telabuscMedicos(){
        BuscaMedicos med = new BuscaMedicos(null, true);
        med.setVisible(true);

        if (med.okselecionado()) {
            Usuario m = med.retornMedSele();
            if (m != null) {
                usuario = m.getId().toString();
                tf_medico.setText(m.getNomeMedico());
                }
            }else{
            cb_medico.setSelectedIndex(0);
            tf_medico.setText("");
        }
        }
    public void telBuscaEmpresa() {
        BuscaEmpresas empr = new BuscaEmpresas(null, true);
        empr.getRootPane().setWindowDecorationStyle(JRootPane.COLOR_CHOOSER_DIALOG);
        empr.setVisible(true);

        if (empr.okselecionado()) {
        Empresa emp = empr.retornCliSele();
        if (emp != null) {
            empresa = emp.getId().toString();
            tf_empresa.setText(emp.getFantasia());
        }
        }else{
            cb_emprea.setSelectedIndex(0);
            tf_empresa.setText("");
        }
        
    }
       
    public void telBuscaConpagt(){
        BuscaCondPagt bc = new BuscaCondPagt(null, true);
       bc.setVisible(true);

        if (bc.okselecionado()) {
            CondPagto c = bc.retornEspSele();
            if (c != null) {
                condPag = c.getId().toString();
                tf_condpgto.setText(c.getCondPagt());
            }
            
        }else {
            cb_condPagt.setSelectedIndex(0);
            tf_condpgto.setText("");
        }
        

       }   
    
    public void telBuscaConvenio(){
         BuscaConvenios tc = new BuscaConvenios(null, true);
        tc.setVisible(true);

        if (tc.okselecionado()) {
            Convenio c = tc.retornEspSele();
            conve= c.getId().toString();
            tf_convenio.setText(c.getDsConvenio());
        }else{
            cb_conv.setSelectedIndex(0);
            tf_convenio.setText("");
        }
        
      
       }
    
    public final java.util.Date converte(String dataConsul) throws ParseException {
        DateFormat forma = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date dat = new java.sql.Date(forma.parse(dataConsul).getTime());

        return dat;
    }
    
    public void gerarRel(){
        
   String emp ;
   String pa ;
   String med ;
   String condp ;
   String conv ;
        try {
            
        CadConsultasDAO c = new CadConsultasDAO();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date data1 =  tf_dataIni.getDate() ;
        java.util.Date data2 = tf_dataFin.getDate();
        String dat1= formato.format(data1);
        String dat2= formato.format(data2);
        Date dataIni =  (Date) converte(dat1);
        Date dataFin = (Date) converte(dat2);
        int st = cb_stat.getSelectedIndex();
        if (cb_paciente.getSelectedIndex() == 0) {
            pa = "";
        }else{
            
            pa = "and pa.id = '"+paciente+"' ";
        }
        if (st == 0) {
            status = "and sts.id in (1,2,3,4,5,6)";
        
        }else{
            status = "and sts.id in ("+st+")";
        }
        
        if (cb_conv.getSelectedIndex() == 0) {
            conv = "";
        }else{
            conv = "and cv.id = '"+conve+"' ";
        }
        if (cb_condPagt.getSelectedIndex() == 0) {
            condp = "";
        }else{
            condp = "and cpgto.id = '"+condPag+"' ";
        }if (cb_medico.getSelectedIndex() == 0) {
            med = "";
        }else{
            med = "and usu.id = '"+usuario+"' ";
        }if (cb_emprea.getSelectedIndex() == 0) {
            emp = "";
        }else{
            emp = "and con.id_empresa = '"+empresa+"' ";
        }
            switch (cb_ordem.getSelectedIndex()) {
                case 0:
                    ordem = "data_consulta";
                    break;
                case 1:
                    ordem = "nome";
                    break;
                case 2:
                    ordem = "ds_convenio";
                    break;
                case 3:
                    ordem = "descricao";
                    break;
               case 4:
                    ordem = "ds_status";
                    break;
                default:
                    ordem = "data_consulta";
            }
            Clinica e = Sessao.getInstance().getClinica();
        c.ConectRelatorio((java.sql.Date) dataIni, (java.sql.Date) dataFin, pa, status, conv, condp, med, ordem,e.getId(),emp);
    } catch (ParseException ex) {
       
             JOptionPane.showMessageDialog(null, "Data inválida!");
    } 
    }
}
