/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.markConsult.gui;

import br.com.markConsult.dao.AlteraImagemDAO;
import br.com.markConsult.classesMetodos.BackGround;
import br.com.markConsult.dao.CadUsuarioDAO;
import br.com.markConsult.dao.Desktop;
import br.com.markConsult.entidades.MinhaEmpresa;
import br.com.markConsult.entidades.Sessao;
import br.com.markConsult.entidades.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jeferson
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private final Properties confBanco = new Properties();
    Desktop desk = new Desktop();
    Boolean escBarra;
    BackGround background = null;
    int trocar = 1;
    Usuario u;
    MinhaEmpresa minnhaEmpresa;
    String data = (new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date(System.currentTimeMillis())));

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();            
                

        lbData.setText(" " + data);
        u = Sessao.getInstance().getUsuario();
        minnhaEmpresa = Sessao.getInstance().getMinhaEmpresa();
        if (u != null) {
            lb_usuario.setText(u.getNome());
            escBarra = u.isEscBarra();
            if (u.getCodTema() != 8) {
                mudaAparencia(u.getCodTema());
            }

        }

        if (minnhaEmpresa != null) {
            jL_empresa.setText(minnhaEmpresa.getFantasia());

        }


        if (u.isHeAdm()) {
            jmiCadUsuario.setVisible(true);
        } else {
            jmiCadUsuario.setVisible(false);
        }
        if (u.getCodTema() == 8) {
            addpopup();
        }

        escBlo();

        // coloca uma figura na barra de título da janela  
        URL url = this.getClass().getResource("/br/com/markConsult/imagens/help.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);  
         this.addWindowListener(new java.awt.event.WindowAdapter() {  
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {  
                    if (e.getID() == WindowEvent.WINDOW_CLOSING){  
                       fecharTela();
                }  
            }});
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupBarra = new javax.swing.JPopupMenu();
        jMEsconder = new javax.swing.JMenuItem();
        jMBloquear = new javax.swing.JMenuItem();
        lb_usuario = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        desktopPane =  background = new BackGround();
        desktopPane =  background;
        barraFerrament = new javax.swing.JToolBar();
        btCadPaciente = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btRelCon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_barra = new javax.swing.JLabel();
        jL_empresa = new javax.swing.JLabel();
        menu_principal = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        jmiCadUsuario = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jmiAlteraSenh = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuEmpresas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu_pcmso = new javax.swing.JMenu();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemSetores = new javax.swing.JMenuItem();
        jMenuItemFuncoes = new javax.swing.JMenuItem();
        jMenuItemTipoRisco = new javax.swing.JMenuItem();
        jMenuItemRiscos = new javax.swing.JMenuItem();
        jMenuItemExames = new javax.swing.JMenuItem();
        jMenuItemPeriodicidade = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menu_item_Paciente = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jM_cadastro_empresas = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBuscaOrdens = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuTema = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuIAluminium = new javax.swing.JMenuItem();
        jMenuIAcrylLook = new javax.swing.JMenuItem();
        jMenuIGraphite = new javax.swing.JMenuItem();
        jMenuILuna = new javax.swing.JMenuItem();
        jMenuIMint = new javax.swing.JMenuItem();
        jMenuIMcWinLook = new javax.swing.JMenuItem();
        jMenuAero = new javax.swing.JMenuItem();
        salvaArquivo = new javax.swing.JMenuItem();

        jMEsconder.setText("Esconder Barra");
        jMEsconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEsconderActionPerformed(evt);
            }
        });
        jPopupBarra.add(jMEsconder);

        jMBloquear.setText("Bloquear Barra");
        jMBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBloquearActionPerformed(evt);
            }
        });
        jPopupBarra.add(jMBloquear);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEUROCENTER");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        lb_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        desktopPane.setOpaque(false);
        desktopPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                desktopPaneMouseMoved(evt);
            }
        });

        barraFerrament.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        barraFerrament.setFloatable(false);
        barraFerrament.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barraFerrament.setRollover(true);
        barraFerrament.setAutoscrolls(true);
        barraFerrament.setPreferredSize(new java.awt.Dimension(48, 800));

        btCadPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/cliente.png"))); // NOI18N
        btCadPaciente.setToolTipText("Cadastro de Paciente");
        btCadPaciente.setFocusable(false);
        btCadPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadPacienteActionPerformed(evt);
            }
        });
        barraFerrament.add(btCadPaciente);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/BuscaConsultas.png"))); // NOI18N
        jButton4.setToolTipText("Lista Consultas");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        barraFerrament.add(jButton4);

        btRelCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/relatórios.png"))); // NOI18N
        btRelCon.setToolTipText("Relatório de Ordens");
        btRelCon.setFocusable(false);
        btRelCon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRelCon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRelCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelConActionPerformed(evt);
            }
        });
        barraFerrament.add(btRelCon);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/password.png"))); // NOI18N
        jButton2.setToolTipText("Alterar Senha");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        barraFerrament.add(jButton2);

        desktopPane.add(barraFerrament);
        barraFerrament.setBounds(0, 0, 60, 450);

        lb_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_barraMouseMoved(evt);
            }
        });
        desktopPane.add(lb_barra);
        lb_barra.setBounds(0, 0, 1, 700);

        jL_empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_empresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menu_principal.setPreferredSize(new java.awt.Dimension(398, 20));

        menu_cadastros.setMnemonic('C');
        menu_cadastros.setText("Cadastros");
        menu_cadastros.setBorderPainted(true);
        menu_cadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_cadastros.setPreferredSize(new java.awt.Dimension(70, 76));

        menuUsuario.setMnemonic('U');
        menuUsuario.setText("Usuários");

        jmiCadUsuario.setText("Cadastro de usuário");
        jmiCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(jmiCadUsuario);
        menuUsuario.add(jSeparator9);

        jmiAlteraSenh.setText("Alterar senha");
        jmiAlteraSenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlteraSenhActionPerformed(evt);
            }
        });
        menuUsuario.add(jmiAlteraSenh);

        menu_cadastros.add(menuUsuario);
        menu_cadastros.add(jSeparator10);

        menuEmpresas.setText("Minha empresa");
        menuEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresasActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuEmpresas);

        jMenuItem2.setText("ASO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_cadastros.add(jMenuItem2);

        menu_principal.add(menu_cadastros);

        jMenu_pcmso.setText("PCMSO");

        jMenuCadastros.setText("Cadastros");

        jMenuItemSetores.setText("Setores");
        jMenuItemSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetoresActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemSetores);

        jMenuItemFuncoes.setText("Funções");
        jMenuItemFuncoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncoesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFuncoes);

        jMenuItemTipoRisco.setText("Tipo de Risco");
        jMenuItemTipoRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoRiscoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemTipoRisco);

        jMenuItemRiscos.setText("Riscos");
        jMenuItemRiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRiscosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemRiscos);

        jMenuItemExames.setText("Exames");
        jMenuItemExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExamesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemExames);

        jMenuItemPeriodicidade.setText("Periodicidade");
        jMenuItemPeriodicidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeriodicidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemPeriodicidade);

        jMenu_pcmso.add(jMenuCadastros);
        jMenu_pcmso.add(jSeparator11);

        menu_item_Paciente.setText("Pacientes");
        menu_item_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_PacienteActionPerformed(evt);
            }
        });
        jMenu_pcmso.add(menu_item_Paciente);
        jMenu_pcmso.add(jSeparator13);

        jM_cadastro_empresas.setText("Cadastro de empresas");
        jM_cadastro_empresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_cadastro_empresasActionPerformed(evt);
            }
        });
        jMenu_pcmso.add(jM_cadastro_empresas);
        jMenu_pcmso.add(jSeparator14);

        jMenuItem1.setText("Cadastro de PCMSO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_pcmso.add(jMenuItem1);

        menu_principal.add(jMenu_pcmso);

        jMenu3.setText("Ordens");

        jMenuItem7.setText("Ordem para exames");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);
        jMenu3.add(jSeparator12);

        jMenuItemBuscaOrdens.setText("Busca Ordens");
        jMenuItemBuscaOrdens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscaOrdensActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemBuscaOrdens);

        menu_principal.add(jMenu3);

        jMenu2.setMnemonic('R');
        jMenu2.setText("Relatórios");
        jMenu2.setBorderPainted(true);
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setPreferredSize(new java.awt.Dimension(70, 76));

        jMenuItem3.setText("Ordens para exames");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menu_principal.add(jMenu2);

        jMenu1.setMnemonic('s');
        jMenu1.setText("Sair");
        jMenu1.setBorderPainted(true);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menu_principal.add(jMenu1);

        jMenu6.setText("Ajuda");

        jMenuItemAjuda.setText("Contato");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAjuda);

        jMenu7.setText("Aparência do sistema");

        jMenuItem5.setText("Imagem de fundo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuTema.setText("Tema");

        jMenuItem4.setText("Padrão");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuItem4);

        jMenuIAluminium.setText("Aluminium");
        jMenuIAluminium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIAluminiumActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuIAluminium);

        jMenuIAcrylLook.setText("AcrylLook");
        jMenuIAcrylLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIAcrylLookActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuIAcrylLook);

        jMenuIGraphite.setText("Graphite");
        jMenuIGraphite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIGraphiteActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuIGraphite);

        jMenuILuna.setText("Luna");
        jMenuILuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuILunaActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuILuna);

        jMenuIMint.setText("Mint");
        jMenuIMint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIMintActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuIMint);

        jMenuIMcWinLook.setText("McWinLook");
        jMenuIMcWinLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIMcWinLookActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuIMcWinLook);

        jMenuAero.setText("Aero");
        jMenuAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAeroActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuAero);

        jMenu7.add(jMenuTema);

        jMenu6.add(jMenu7);

        salvaArquivo.setText("Backup");
        salvaArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaArquivoActionPerformed(evt);
            }
        });
        jMenu6.add(salvaArquivo);

        menu_principal.add(jMenu6);

        setJMenuBar(menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jL_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lb_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jL_empresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        desktopPane.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
      fecharTela();

    }//GEN-LAST:event_jMenu1MouseClicked

    private void menu_item_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_PacienteActionPerformed

        if (abreFrame("CadPaciente") == null) {
            desk.createFrame(new CadPaciente(), desktopPane);
        }


    }//GEN-LAST:event_menu_item_PacienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (abreFrame("RelaOrdens") == null) {
            desk.createFrame(new RelaOrdens(), desktopPane);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadUsuarioActionPerformed
        if (abreFrame("CadUsuario") == null) {
            desk.createFrame(new CadUsuario(), desktopPane);
        }
    }//GEN-LAST:event_jmiCadUsuarioActionPerformed

    private void jmiAlteraSenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlteraSenhActionPerformed
        if (abreFrame("TrocSenhaUso") == null) {
            desk.createFrame(new TrocSenhaUso(), desktopPane);
        }
    }//GEN-LAST:event_jmiAlteraSenhActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if (escBarra == true) {
            barraFerrament.setVisible(false);
        }
    }//GEN-LAST:event_formMouseMoved

    private void jMEsconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEsconderActionPerformed
        escBarra = true;
        CadUsuarioDAO dao = new CadUsuarioDAO();
        Usuario usu = new Usuario(u.getId(), true);
        dao.escBlocBarra(usu);
        escBlo();
    }//GEN-LAST:event_jMEsconderActionPerformed

    private void jMBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBloquearActionPerformed
        escBarra = false;
        CadUsuarioDAO dao = new CadUsuarioDAO();
        Usuario usu = new Usuario(u.getId(), false);
        dao.escBlocBarra(usu);
        escBlo();
    }//GEN-LAST:event_jMBloquearActionPerformed

    private void menuEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresasActionPerformed
        if (abreFrame("CadMinhaEmpresa") == null) {
            desk.createFrame(new CadMinhaEmpresa(), desktopPane);
        }
    }//GEN-LAST:event_menuEmpresasActionPerformed

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        Ajuda ajuda = new Ajuda(this, true);
        ajuda.setVisible(true);

    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void desktopPaneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopPaneMouseMoved
        if (escBarra == true) {
            barraFerrament.setVisible(false);
        }
    }//GEN-LAST:event_desktopPaneMouseMoved

    private void lb_barraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_barraMouseMoved
        if (escBarra == true) {
            barraFerrament.setVisible(true);
        }
    }//GEN-LAST:event_lb_barraMouseMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (abreFrame("TrocSenhaUso") == null) {
            desk.createFrame(new TrocSenhaUso(), desktopPane);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btRelConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelConActionPerformed
        if (abreFrame("RelaOrdens") == null) {
            desk.createFrame(new RelaOrdens(), desktopPane);
        }
    }//GEN-LAST:event_btRelConActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (abreFrame("BuscaOrdem") == null) {
           desk.createFrame(new BuscaOrdem(), desktopPane);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadPacienteActionPerformed
        if (abreFrame("CadPaciente") == null) {
            desk.createFrame(new CadPaciente(), desktopPane);
        }
    }//GEN-LAST:event_btCadPacienteActionPerformed

    private void jMenuIAluminiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIAluminiumActionPerformed

        mudaAparencia(1);
    }//GEN-LAST:event_jMenuIAluminiumActionPerformed

    private void jMenuIAcrylLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIAcrylLookActionPerformed

        mudaAparencia(2);
    }//GEN-LAST:event_jMenuIAcrylLookActionPerformed

    private void jMenuIMcWinLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIMcWinLookActionPerformed

        mudaAparencia(3);
    }//GEN-LAST:event_jMenuIMcWinLookActionPerformed

    private void jMenuAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAeroActionPerformed

        mudaAparencia(4);
    }//GEN-LAST:event_jMenuAeroActionPerformed

    private void jMenuIGraphiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIGraphiteActionPerformed

        mudaAparencia(5);
    }//GEN-LAST:event_jMenuIGraphiteActionPerformed

    private void jMenuILunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuILunaActionPerformed

        mudaAparencia(6);
    }//GEN-LAST:event_jMenuILunaActionPerformed

    private void jMenuIMintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIMintActionPerformed

        mudaAparencia(7);
    }//GEN-LAST:event_jMenuIMintActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CadUsuarioDAO dao = new CadUsuarioDAO();
        Usuario usu = new Usuario(u.getId(), 8);
        dao.alteraTema(usu);
        JOptionPane.showMessageDialog(null, "Reinicie a aplicação para voltar o tema padrão!");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Importar imagem");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        // int a = fileChooser.showOpenDialog(null);    

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String endImage = fileChooser.getSelectedFile().getPath();
            AlteraImagemDAO dao = new AlteraImagemDAO();
            dao.altImagem(endImage);
            setImage(endImage);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void salvaArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaArquivoActionPerformed

        File arq = new File("neurocenter.backup");
        try {
            createSaveDialog(arq);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_salvaArquivoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if (abreFrame("CadPCMSO") == null) {
            desk.createFrame(new CadPCMSO(),desktopPane);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (abreFrame("GeraOrdem") == null) {
            desk.createFrame(new GeraOrdem(),desktopPane);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jM_cadastro_empresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_cadastro_empresasActionPerformed

        if (abreFrame("CadEmpresa") == null) {
            desk.createFrame(new CadEmpresa(), desktopPane);
        }

    }//GEN-LAST:event_jM_cadastro_empresasActionPerformed

    private void jMenuItemSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetoresActionPerformed
      if (abreFrame("CadSetor") == null) {
            desk.createFrame(new CadSetor(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemSetoresActionPerformed

    private void jMenuItemFuncoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncoesActionPerformed
      if (abreFrame("CadFuncao") == null) {
            desk.createFrame(new CadFuncao(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemFuncoesActionPerformed

    private void jMenuItemRiscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRiscosActionPerformed
       if (abreFrame("CadRisco") == null) {
            desk.createFrame(new CadRisco(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemRiscosActionPerformed

    private void jMenuItemExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExamesActionPerformed
       if (abreFrame("CadExame") == null) {
            desk.createFrame(new CadExame(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemExamesActionPerformed

    private void jMenuItemTipoRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoRiscoActionPerformed
       if (abreFrame("CadTipoRisco") == null) {
            desk.createFrame(new CadTipoRisco(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemTipoRiscoActionPerformed

    private void jMenuItemPeriodicidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeriodicidadeActionPerformed
        if (abreFrame("CadPeriodicidade") == null) {
            desk.createFrame(new CadPeriodicidade(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemPeriodicidadeActionPerformed

    private void jMenuItemBuscaOrdensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscaOrdensActionPerformed
       if (abreFrame("BuscaOrdem") == null) {
            desk.createFrame(new BuscaOrdem(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItemBuscaOrdensActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (abreFrame("CadASO") == null) {
            desk.createFrame(new CadASO(), desktopPane);
        } 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerrament;
    private javax.swing.JButton btCadPaciente;
    private javax.swing.JButton btRelCon;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jL_empresa;
    private javax.swing.JMenuItem jMBloquear;
    private javax.swing.JMenuItem jMEsconder;
    private javax.swing.JMenuItem jM_cadastro_empresas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuAero;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuIAcrylLook;
    private javax.swing.JMenuItem jMenuIAluminium;
    private javax.swing.JMenuItem jMenuIGraphite;
    private javax.swing.JMenuItem jMenuILuna;
    private javax.swing.JMenuItem jMenuIMcWinLook;
    private javax.swing.JMenuItem jMenuIMint;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemBuscaOrdens;
    private javax.swing.JMenuItem jMenuItemExames;
    private javax.swing.JMenuItem jMenuItemFuncoes;
    private javax.swing.JMenuItem jMenuItemPeriodicidade;
    private javax.swing.JMenuItem jMenuItemRiscos;
    private javax.swing.JMenuItem jMenuItemSetores;
    private javax.swing.JMenuItem jMenuItemTipoRisco;
    private javax.swing.JMenu jMenuTema;
    private javax.swing.JMenu jMenu_pcmso;
    private javax.swing.JPopupMenu jPopupBarra;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem jmiAlteraSenh;
    private javax.swing.JMenuItem jmiCadUsuario;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lb_barra;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JMenuItem menuEmpresas;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenuItem menu_item_Paciente;
    private javax.swing.JMenuBar menu_principal;
    private javax.swing.JMenuItem salvaArquivo;
    // End of variables declaration//GEN-END:variables

//public void permicao(){ 
//        CadUsuarioDAO dao = new CadUsuarioDAO();
//        Usuario u = dao.procuraPorUsu(Sessao.getInstance().getUsuario().getNome());
//        if (u != null) {
//            if (u.isHeAdm()) {
//            jmiCadUsuario.setVisible(true);
//        }else{
//            jmiCadUsuario.setVisible(false); 
//            }
//        }
//}
    private void addpopup() {
        barraFerrament.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                //Verificando se o botão direito foi pressionado  
                if ((e.getModifiers() & MouseEvent.BUTTON3_MASK) != 0) {

                    jPopupBarra.show(barraFerrament, e.getX(), e.getY());
                }
            }
        });
    }

    private void escBlo() {
        if (escBarra) {
            jMBloquear.setEnabled(true);
            jMEsconder.setEnabled(false);
        } else {
            jMBloquear.setEnabled(false);
            jMEsconder.setEnabled(true);
        }

    }

    public void setImage(String imagem) {

        background.setImage(imagem);
        background.repaint();
    }

    private void mudaAparencia(int tema) {

        if (desktopPane.getAllFrames().length > 0) {
            JOptionPane.showMessageDialog(null, "Feche todas as telas abertas e tente novamente! ");
        } else {

            String look = null;
            Properties props = new Properties();
            props.put("logoString", "NEUROCENTER");

            try {
                switch (tema) {
                    case 1:
                        com.jtattoo.plaf.aluminium.AluminiumLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.aluminium.AluminiumLookAndFeel";
                        alterarUsuTema(1);
                        break;
                    case 2:
                        com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.acryl.AcrylLookAndFeel";
                        alterarUsuTema(2);
                        break;
                    case 3:
                        com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.mcwin.McWinLookAndFeel";
                        alterarUsuTema(3);
                        break;
                    case 4:
                        com.jtattoo.plaf.aero.AeroLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.aero.AeroLookAndFeel";
                        alterarUsuTema(4);
                        break;
                    case 5:
                        com.jtattoo.plaf.graphite.GraphiteLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.graphite.GraphiteLookAndFeel";
                        alterarUsuTema(5);
                        break;
                    case 6:
                        com.jtattoo.plaf.luna.LunaLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.luna.LunaLookAndFeel";
                        alterarUsuTema(6);
                        break;
                    case 7:
                        com.jtattoo.plaf.mint.MintLookAndFeel.setTheme(props);
                        look = "com.jtattoo.plaf.mint.MintLookAndFeel";
                        alterarUsuTema(7);
                        break;
                    default:
                        throw new AssertionError();
                }
                UIManager.setLookAndFeel(look);
                SwingUtilities.updateComponentTreeUI(this);
            } catch (InstantiationException | ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException o) {
            }

            this.repaint();
            //frame.pack();-não usar!        
        }
    }//fim de mudaAparencia()

    public void alterarUsuTema(int idTema) {
        CadUsuarioDAO dao = new CadUsuarioDAO();
        Usuario usu = new Usuario(u.getId(), idTema);
        dao.alteraTema(usu);
    }

    public JInternalFrame abreFrame(String tela) {
        JInternalFrame frame = null;

        for (JInternalFrame col : desktopPane.getAllFrames()) {
            if (col.getClass().getSimpleName().equals(tela)) {
                frame = col;

            }

        }
        if (frame != null) {
            if (frame.isIcon()) {
                try {
                    frame.setIcon(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                frame.toFront();
            }
        }
        return frame;

    }
    
    private void fecharTela(){
         int selectedOption = JOptionPane.showConfirmDialog(null,"Deseja sair realmente?", "Sistema informa:", JOptionPane.YES_NO_OPTION);  
        if(selectedOption == JOptionPane.YES_OPTION){  
              
            System.exit(0);                           
              } 
    }

    
   

    private void createSaveDialog(File selectedFile) throws IOException, InterruptedException {
        JFileChooser janela = new JFileChooser();  
    File arq = new File("neurocenter.backup");
    if (selectedFile != null) { // Se o arquivo inicial foi especificado, seta no FileChooser  
        janela.setSelectedFile(arq);  
    }
       int resultado = janela.showSaveDialog(this);  
       File file = janela.getSelectedFile();  
       if(resultado == JFileChooser.APPROVE_OPTION){  
           if(file.exists()){  
               int response = JOptionPane.showConfirmDialog(this, "Substituir o arquivo existente?", "Confirmar substituição", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);  
                   if (response == JOptionPane.YES_OPTION) {
                    System.out.println("salvar mesmo assim");
                    realizaBackup(file.getPath());
               }
               
                    
               if (response == JOptionPane.CANCEL_OPTION) {  
                 createSaveDialog(janela.getSelectedFile()); // Se o usuário cancelar, chama o método novamente para abrir um FileChooser já com o arquivo selecionado.  
              
               }
           }else{
        System.out.println("salvo");
        System.out.println(file.getAbsolutePath());
        realizaBackup(file.getPath());
         
       } 
    }
    
    }
    
    public static void realizaBackup(String diretorio) throws IOException, InterruptedException{        
           final List<String> comandos = new ArrayList<>();        
               
           //comandos.add("C:\\Program Files (x86)\\PostgreSQL\\8.4\\bin\\pg_dump.exe");   
          //comandos.add("C:\\Program Files\\PostgresPlus\\8.4SS\\bin\\pg_dump.exe");   
           comandos.add("C:\\Program Files\\PostgreSQL\\9.1\\bin\\pg_dump.exe");    // esse é meu caminho    
             
           comandos.add("-i");        
           comandos.add("-h");        
           comandos.add("localhost");     //ou  comandos.add("192.168.0.1");   
           comandos.add("-p");        
           comandos.add("5432");        
           comandos.add("-U");        
           comandos.add("postgres");        
           comandos.add("-F");        
           comandos.add("c");        
           comandos.add("-b");        
           comandos.add("-v");        
           comandos.add("-f");        
               
           comandos.add(diretorio);   // eu utilizei meu C:\ e D:\ para os testes e gravei o backup com sucesso.    
           comandos.add("neurocenter");        
           ProcessBuilder pb = new ProcessBuilder(comandos);        
               
           pb.environment().put("PGPASSWORD", "bg7mkib");      //Somente coloque sua senha           
               
           try {        
               final Process process = pb.start();        
           
               final BufferedReader r = new BufferedReader(        
                   new InputStreamReader(process.getErrorStream()));        
               String line = r.readLine();        
               while (line != null) {        
               System.err.println(line);        
               line = r.readLine();        
               }        
               r.close();        
           
               process.waitFor();      
               process.destroy();   
               JOptionPane.showMessageDialog(null,"backup realizado com sucesso.");    
           
           } catch (IOException | InterruptedException e) {        
           }           
                 
       }        
          
    
}
