/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.markConsult.gui;
import br.com.markConsult.classesMetodos.ConsultaProcedimentosTableModel;
import br.com.markConsult.dao.CadConsultasDAO;
import br.com.markConsult.entidades.Consulta;
import br.com.markConsult.entidades.ConsultaProcedimento;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jeferson
 */
public class VerProcedimentosConsulta extends javax.swing.JDialog {
     private Consulta consulta;
     private ConsultaProcedimentosTableModel modelProcedimento;
    /**
     * Creates new form VerProcedimentosConsulta
     * @param parent
     * @param modal
     */
    public VerProcedimentosConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        URL url = this.getClass().getResource("/br/com/markConsult/imagens/help.png");  
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(imagemTitulo);
        modelProcedimento = new ConsultaProcedimentosTableModel();
        jTConsultas.setModel(modelProcedimento);
        ajusTabela();
        
        TableRowSorter<ConsultaProcedimentosTableModel> sorter = new TableRowSorter<>((ConsultaProcedimentosTableModel) jTConsultas.getModel());  
            jTConsultas.setRowSorter(sorter);
        
        
        JTableHeader header = jTConsultas.getTableHeader();  
        header.addMouseListener(new MouseAdapter() {  
  
            @Override  
            public void mouseClicked(MouseEvent e) {  
                JTable table = ((JTableHeader) e.getSource()).getTable();  
                TableColumnModel colModel = table.getColumnModel();  
                int vColIndex = colModel.getColumnIndexAtX(e.getX());  
                int mColIndex = table.convertColumnIndexToModel(vColIndex);  
                if (vColIndex == -1) {  
                    return;  
                }  
                int ordenacao = mColIndex; //criei esta váriavel ordenacao;  
            }  
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsultas = new javax.swing.JTable();
        bt_sair = new javax.swing.JButton();
        bt_realizada = new javax.swing.JButton();
        bt_falta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jl_nomePaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procedimentos");

        jTConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTConsultas);

        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/markConsult/imagens/Log-Out-icon.png"))); // NOI18N
        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        bt_realizada.setText("MARCAR COMO REALIZADO");
        bt_realizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_realizadaActionPerformed(evt);
            }
        });

        bt_falta.setText("MARCAR COMO FALTA");
        bt_falta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_faltaActionPerformed(evt);
            }
        });

        jLabel1.setText("Paciente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_realizada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_falta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_nomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_nomePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_sair)
                    .addComponent(bt_realizada)
                    .addComponent(bt_falta))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_realizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_realizadaActionPerformed
     alteraStatus("REALIZADO");
    }//GEN-LAST:event_bt_realizadaActionPerformed

    private void bt_faltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_faltaActionPerformed
         alteraStatus("FALTA");
    }//GEN-LAST:event_bt_faltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProcedimentosConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            VerProcedimentosConsulta dialog = new VerProcedimentosConsulta(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_falta;
    private javax.swing.JButton bt_realizada;
    private javax.swing.JButton bt_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTConsultas;
    private javax.swing.JLabel jl_nomePaciente;
    // End of variables declaration//GEN-END:variables
public void pesquisa() {
        CadConsultasDAO dao = new CadConsultasDAO();
        List<ConsultaProcedimento> procedimentos = dao.BuscaProcedimetoEmpresa("", 'e',this.consulta.getId());
        modelProcedimento.listar(procedimentos);
        ajusTabela();
    }

    private void ajusTabela() {
//        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
//        direita.setHorizontalAlignment(SwingConstants.RIGHT);
//
//        jTConsultas.getColumnModel().getColumn(0).setMinWidth(60);
//        jTConsultas.getColumnModel().getColumn(0).setMaxWidth(60);
//        jTConsultas.getColumnModel().getColumn(1).setPreferredWidth(200);
//        jTConsultas.getColumnModel().getColumn(2).setPreferredWidth(140);
//        jTConsultas.getColumnModel().getColumn(3).setPreferredWidth(120);
//        jTConsultas.getColumnModel().getColumn(4).setPreferredWidth(60);
//        jTConsultas.getColumnModel().getColumn(4).setCellRenderer(direita);
//        jTConsultas.getColumnModel().getColumn(5).setPreferredWidth(100);
//        jTConsultas.getColumnModel().getColumn(6).setPreferredWidth(100);
//        jTConsultas.getColumnModel().getColumn(7).setPreferredWidth(100);
//        jTConsultas.getColumnModel().getColumn(8).setPreferredWidth(100);
//        jTConsultas.getColumnModel().getColumn(9).setPreferredWidth(200);
//        jTConsultas.getColumnModel().getColumn(10).setPreferredWidth(1000);
    }
   
     
     public void setConsulta(Consulta consulta){
         this.consulta = consulta;
         jl_nomePaciente.setText(consulta.getPaciente().getNome());
         pesquisa();
     }

    private void alteraStatus(String status) {
          CadConsultasDAO dao = new CadConsultasDAO();
        List<ConsultaProcedimento> con = new ArrayList<>();
        modelProcedimento.getProcedimentos().stream().filter((consultaProcedimento) -> (consultaProcedimento.getSelecao())).map((consultaProcedimento) -> {
            consultaProcedimento.setStatus(status);
             return consultaProcedimento;
         }).forEach((consultaProcedimento) -> {
             con.add(consultaProcedimento);
         });
dao.altStatProcedimento(con);
        pesquisa();
    }
}
